-- Auto-generated by export_dvf_3_3_lua_bridge.py.
-- Routing metadata only; IrisLayer3DataChunks remains the public facade.
-- sha256 hashes strict UTF-8 text after CRLF/CR -> LF normalization.
return {
    schema_version = "iris_layer3_chunk_range_index_v1",
    entry_count = 2105,
    chunks = {
        { count = 200, first = "Base.223Box", last = "Base.BookElectrician5", module = "Iris/Data/IrisLayer3Generations/dvf33-028b1189a27295376ef37a5fe855f0886b15ae3d217486f9b5ace93cd3fc5a0c/Chunks/Chunk001", sha256 = "cce45e87367da8c74903159c10ef412a60dbee7a50065697892ba54e50da4941" },
        { count = 200, first = "Base.BookFarming1", last = "Base.ChocoCakes", module = "Iris/Data/IrisLayer3Generations/dvf33-028b1189a27295376ef37a5fe855f0886b15ae3d217486f9b5ace93cd3fc5a0c/Chunks/Chunk002", sha256 = "63736e54514d64b00c094ef5aa5a57eebe37c8a914050cd622e92c8af3cbb231" },
        { count = 200, first = "Base.Chocolate", last = "Base.FishingNet", module = "Iris/Data/IrisLayer3Generations/dvf33-028b1189a27295376ef37a5fe855f0886b15ae3d217486f9b5ace93cd3fc5a0c/Chunks/Chunk003", sha256 = "8443688d9a8fb3f397aa98035b3e9e37c32c967dad22f53c74d4f6e5587246e1" },
        { count = 200, first = "Base.FishingRod", last = "Base.Hat_HockeyHelmet", module = "Iris/Data/IrisLayer3Generations/dvf33-028b1189a27295376ef37a5fe855f0886b15ae3d217486f9b5ace93cd3fc5a0c/Chunks/Chunk004", sha256 = "ec68e1e22863eb6076fcbdc537c73e9a878dfc5c1519f065cad721f153d9afb6" },
        { count = 200, first = "Base.Hat_HockeyMask", last = "Base.MakeUp_CamoFullFace1", module = "Iris/Data/IrisLayer3Generations/dvf33-028b1189a27295376ef37a5fe855f0886b15ae3d217486f9b5ace93cd3fc5a0c/Chunks/Chunk005", sha256 = "09a1a0f976ac6e1d31ff74cc3a90090774dee74b25120bba4940524734303364" },
        { count = 200, first = "Base.MakeUp_CamoFullFace2", last = "Base.Mov_SmallTable", module = "Iris/Data/IrisLayer3Generations/dvf33-028b1189a27295376ef37a5fe855f0886b15ae3d217486f9b5ace93cd3fc5a0c/Chunks/Chunk006", sha256 = "e9a68e6d667c956d202dc856af3dd829b323cbc24bac1230fd8ff3f413d8fe79" },
        { count = 200, first = "Base.Mov_SodaMachine", last = "Base.PillsVitamins", module = "Iris/Data/IrisLayer3Generations/dvf33-028b1189a27295376ef37a5fe855f0886b15ae3d217486f9b5ace93cd3fc5a0c/Chunks/Chunk007", sha256 = "a5cd1b6fe781811ca088767ff6f1f848bb238166043d26f409a36055793fdf59" },
        { count = 200, first = "Base.Pineapple", last = "Base.Shirt_Bowling_White", module = "Iris/Data/IrisLayer3Generations/dvf33-028b1189a27295376ef37a5fe855f0886b15ae3d217486f9b5ace93cd3fc5a0c/Chunks/Chunk008", sha256 = "6a849a79228b4e0ff3e7c9e3ef96a3740ee0e4ea28f6dea51c03ef30f8552522" },
        { count = 200, first = "Base.Shirt_CamoDesert", last = "Base.Tissue", module = "Iris/Data/IrisLayer3Generations/dvf33-028b1189a27295376ef37a5fe855f0886b15ae3d217486f9b5ace93cd3fc5a0c/Chunks/Chunk009", sha256 = "08a25b18c676650e833f23acd8ae0c84351df732f7a05c1f1e3196541d5b2d19" },
        { count = 200, first = "Base.Toast", last = "Base.WineInGlass", module = "Iris/Data/IrisLayer3Generations/dvf33-028b1189a27295376ef37a5fe855f0886b15ae3d217486f9b5ace93cd3fc5a0c/Chunks/Chunk010", sha256 = "793649e658c966fced6474770214bceaf67f62a53e56251dc01dc5102344db55" },
        { count = 105, first = "Base.WinePetrol", last = "farming.WateredCanFull", module = "Iris/Data/IrisLayer3Generations/dvf33-028b1189a27295376ef37a5fe855f0886b15ae3d217486f9b5ace93cd3fc5a0c/Chunks/Chunk011", sha256 = "5dc861e38048da7c7e1438afe62701ae2ae364239409650b93ad5fde25ad64d9" },
    },
}
