-- Auto-generated by export_dvf_3_3_lua_bridge.py.
-- Routing metadata only; IrisLayer3DataChunks remains the public facade.
-- sha256 hashes strict UTF-8 text after CRLF/CR -> LF normalization.
return {
    schema_version = "iris_layer3_chunk_range_index_v1",
    entry_count = 2105,
    chunks = {
        { count = 200, first = "Base.223Box", last = "Base.BookElectrician5", module = "Iris/Data/IrisLayer3Generations/dvf33-aa138aa4896b68ac53609a4b1cb6e5346245e74f544db28eb2ee924dc7b3e814/Chunks/Chunk001", sha256 = "69e71609029c0a1dd345d83ab09113bf6ceadec08f7a20e0217f7cf1c445af1a" },
        { count = 200, first = "Base.BookFarming1", last = "Base.ChocoCakes", module = "Iris/Data/IrisLayer3Generations/dvf33-aa138aa4896b68ac53609a4b1cb6e5346245e74f544db28eb2ee924dc7b3e814/Chunks/Chunk002", sha256 = "6045fefbd8f5b1016a557b328cda1b407e06afabd94bdea3f7b55e4bff3be064" },
        { count = 200, first = "Base.Chocolate", last = "Base.FishingNet", module = "Iris/Data/IrisLayer3Generations/dvf33-aa138aa4896b68ac53609a4b1cb6e5346245e74f544db28eb2ee924dc7b3e814/Chunks/Chunk003", sha256 = "4c4ef642f72a5b5089a7f38e850ef076aeacc849a4a16a74a50a820875bef604" },
        { count = 200, first = "Base.FishingRod", last = "Base.Hat_HockeyHelmet", module = "Iris/Data/IrisLayer3Generations/dvf33-aa138aa4896b68ac53609a4b1cb6e5346245e74f544db28eb2ee924dc7b3e814/Chunks/Chunk004", sha256 = "6e835aa920d4c73d9bff941e039067167a50ad59d4cc9dfbdc72689f9de90cea" },
        { count = 200, first = "Base.Hat_HockeyMask", last = "Base.MakeUp_CamoFullFace1", module = "Iris/Data/IrisLayer3Generations/dvf33-aa138aa4896b68ac53609a4b1cb6e5346245e74f544db28eb2ee924dc7b3e814/Chunks/Chunk005", sha256 = "dd7bd24839ba7917b47d8f81d97d5a84c55b2bb069f15d929b2175aa9d0524c8" },
        { count = 200, first = "Base.MakeUp_CamoFullFace2", last = "Base.Mov_SmallTable", module = "Iris/Data/IrisLayer3Generations/dvf33-aa138aa4896b68ac53609a4b1cb6e5346245e74f544db28eb2ee924dc7b3e814/Chunks/Chunk006", sha256 = "f2f5f01b75475904bd46b6bced3ac5aa9ef39d30801948a776bd5f73ade29677" },
        { count = 200, first = "Base.Mov_SodaMachine", last = "Base.PillsVitamins", module = "Iris/Data/IrisLayer3Generations/dvf33-aa138aa4896b68ac53609a4b1cb6e5346245e74f544db28eb2ee924dc7b3e814/Chunks/Chunk007", sha256 = "032d0d4d96b6e1b86141940c9ef290a3e7cbee8a2a6ecf9051d62da6c27f9777" },
        { count = 200, first = "Base.Pineapple", last = "Base.Shirt_Bowling_White", module = "Iris/Data/IrisLayer3Generations/dvf33-aa138aa4896b68ac53609a4b1cb6e5346245e74f544db28eb2ee924dc7b3e814/Chunks/Chunk008", sha256 = "09f027ed63efc7260787d477c029c3e1228e7a6c6e5cc20216902a276865d59f" },
        { count = 200, first = "Base.Shirt_CamoDesert", last = "Base.Tissue", module = "Iris/Data/IrisLayer3Generations/dvf33-aa138aa4896b68ac53609a4b1cb6e5346245e74f544db28eb2ee924dc7b3e814/Chunks/Chunk009", sha256 = "e1fefebbdbaa7d3edba8b696427c15b0e99970a213fabfab31c1c6fb724cf774" },
        { count = 200, first = "Base.Toast", last = "Base.WineInGlass", module = "Iris/Data/IrisLayer3Generations/dvf33-aa138aa4896b68ac53609a4b1cb6e5346245e74f544db28eb2ee924dc7b3e814/Chunks/Chunk010", sha256 = "f3d6b763aaf6ecd235895e29b9eea5c606b604dd2aa173312ec21a9ea1aa64c0" },
        { count = 105, first = "Base.WinePetrol", last = "farming.WateredCanFull", module = "Iris/Data/IrisLayer3Generations/dvf33-aa138aa4896b68ac53609a4b1cb6e5346245e74f544db28eb2ee924dc7b3e814/Chunks/Chunk011", sha256 = "eede7fdb2104817217df1dc67938691335d882054fd5cd626904d116e0d9e165" },
    },
}
