[pytest]
minversion = 7.0
testpaths =
    Iris/build/description/v2/tests
    Iris/build/tests
python_files = test_*.py
python_classes = *Test Test*
python_functions = test_*
pythonpath =
    .
    Iris/build
addopts = -ra
norecursedirs =
    .git
    .hg
    .svn
    .tox
    .venv
    venv
    __pycache__
    .tmp_tests
    tmp*
    Iris/_archive
    Iris/build/description/v2/.tmp_tests
