-- Auto-generated by export_dvf_3_3_lua_bridge.py.
-- Routing metadata only; IrisLayer3DataChunks remains the public facade.
-- sha256 hashes strict UTF-8 text after CRLF/CR -> LF normalization.
return {
    schema_version = "iris_layer3_chunk_range_index_v1",
    entry_count = 2105,
    chunks = {
        { count = 200, first = "Base.223Box", last = "Base.BookElectrician5", module = "Iris/Data/IrisLayer3Generations/dvf33-103dd029d58267ffa696fcb9fa197d5564d14716f12f6ae3ee398b4fb3b41d83/Chunks/Chunk001", sha256 = "13bdfcc0620b745ef6251ee2c85e45a727df680c815a7f5eca8a5e4ff0a5aab2" },
        { count = 200, first = "Base.BookFarming1", last = "Base.ChocoCakes", module = "Iris/Data/IrisLayer3Generations/dvf33-103dd029d58267ffa696fcb9fa197d5564d14716f12f6ae3ee398b4fb3b41d83/Chunks/Chunk002", sha256 = "46581c1496e4cedf9aeafcf2b46b056d30e01957d3e8ddcdbb0294baa11a9888" },
        { count = 200, first = "Base.Chocolate", last = "Base.FishingNet", module = "Iris/Data/IrisLayer3Generations/dvf33-103dd029d58267ffa696fcb9fa197d5564d14716f12f6ae3ee398b4fb3b41d83/Chunks/Chunk003", sha256 = "0956daa7cdcdc362e294c0f825639c5daecc7138cdaf7066628fba4651f2c99f" },
        { count = 200, first = "Base.FishingRod", last = "Base.Hat_HockeyHelmet", module = "Iris/Data/IrisLayer3Generations/dvf33-103dd029d58267ffa696fcb9fa197d5564d14716f12f6ae3ee398b4fb3b41d83/Chunks/Chunk004", sha256 = "77933b4db7429684cfe22fbb1f43b82fb608f63a8cdd34435d8b0adce5993728" },
        { count = 200, first = "Base.Hat_HockeyMask", last = "Base.MakeUp_CamoFullFace1", module = "Iris/Data/IrisLayer3Generations/dvf33-103dd029d58267ffa696fcb9fa197d5564d14716f12f6ae3ee398b4fb3b41d83/Chunks/Chunk005", sha256 = "10302cf821e1fe10c6d62b1e7286d42687d19e0fc0941869a5c8a25633e26357" },
        { count = 200, first = "Base.MakeUp_CamoFullFace2", last = "Base.Mov_SmallTable", module = "Iris/Data/IrisLayer3Generations/dvf33-103dd029d58267ffa696fcb9fa197d5564d14716f12f6ae3ee398b4fb3b41d83/Chunks/Chunk006", sha256 = "d24d8bf406d7e9dd14073f4317f3f221b08f88dfa6c3616f3dd4741dd3f69bb5" },
        { count = 200, first = "Base.Mov_SodaMachine", last = "Base.PillsVitamins", module = "Iris/Data/IrisLayer3Generations/dvf33-103dd029d58267ffa696fcb9fa197d5564d14716f12f6ae3ee398b4fb3b41d83/Chunks/Chunk007", sha256 = "ec862f1e6ff6ccef28b7b65c85bc0c18ff2595b5e585e8e809027eaa40f6fec3" },
        { count = 200, first = "Base.Pineapple", last = "Base.Shirt_Bowling_White", module = "Iris/Data/IrisLayer3Generations/dvf33-103dd029d58267ffa696fcb9fa197d5564d14716f12f6ae3ee398b4fb3b41d83/Chunks/Chunk008", sha256 = "ac10126185aed24f9adbd6a4ce7c5ffd7c71a306c029b56965d063f4d85134a7" },
        { count = 200, first = "Base.Shirt_CamoDesert", last = "Base.Tissue", module = "Iris/Data/IrisLayer3Generations/dvf33-103dd029d58267ffa696fcb9fa197d5564d14716f12f6ae3ee398b4fb3b41d83/Chunks/Chunk009", sha256 = "217ce1d9bced4e6cd9c24296422886ba0c3c30e2143ddd672168a3b7d7e17f73" },
        { count = 200, first = "Base.Toast", last = "Base.WineInGlass", module = "Iris/Data/IrisLayer3Generations/dvf33-103dd029d58267ffa696fcb9fa197d5564d14716f12f6ae3ee398b4fb3b41d83/Chunks/Chunk010", sha256 = "b1fed628c8d83df547370310ec2969098552148bc62df8c62ce99b175753f336" },
        { count = 105, first = "Base.WinePetrol", last = "farming.WateredCanFull", module = "Iris/Data/IrisLayer3Generations/dvf33-103dd029d58267ffa696fcb9fa197d5564d14716f12f6ae3ee398b4fb3b41d83/Chunks/Chunk011", sha256 = "9c7130a60bd3bedcbe1e22e683af5080a25bc4aad2a56f8e24f2725807455d49" },
    },
}
