-- Auto-generated by export_dvf_3_3_lua_bridge.py.
-- Routing metadata only; IrisLayer3DataChunks remains the public facade.
-- sha256 hashes strict UTF-8 text after CRLF/CR -> LF normalization.
return {
    schema_version = "iris_layer3_chunk_range_index_v1",
    entry_count = 2105,
    chunks = {
        { count = 200, first = "Base.223Box", last = "Base.BookElectrician5", module = "Iris/Data/IrisLayer3Generations/dvf33-0f79744533b1316c5d92f876aaffe9d540fe315dca40c1ca4271e5ad8c1bc16d/Chunks/Chunk001", sha256 = "63d1377d2b1c5eae5f09d6f4eaee8d5f44a2656e71a171396b625fbb7eb0dd32" },
        { count = 200, first = "Base.BookFarming1", last = "Base.ChocoCakes", module = "Iris/Data/IrisLayer3Generations/dvf33-0f79744533b1316c5d92f876aaffe9d540fe315dca40c1ca4271e5ad8c1bc16d/Chunks/Chunk002", sha256 = "739f90c9765bab8a0dfddda9c147196e3cad6e9b01e8dfae4f6a3f85aa4ce0a1" },
        { count = 200, first = "Base.Chocolate", last = "Base.FishingNet", module = "Iris/Data/IrisLayer3Generations/dvf33-0f79744533b1316c5d92f876aaffe9d540fe315dca40c1ca4271e5ad8c1bc16d/Chunks/Chunk003", sha256 = "6eac49cc9b5252a20a59e9a039575526550510b90f4b45c7de668bfa062291cf" },
        { count = 200, first = "Base.FishingRod", last = "Base.Hat_HockeyHelmet", module = "Iris/Data/IrisLayer3Generations/dvf33-0f79744533b1316c5d92f876aaffe9d540fe315dca40c1ca4271e5ad8c1bc16d/Chunks/Chunk004", sha256 = "77933b4db7429684cfe22fbb1f43b82fb608f63a8cdd34435d8b0adce5993728" },
        { count = 200, first = "Base.Hat_HockeyMask", last = "Base.MakeUp_CamoFullFace1", module = "Iris/Data/IrisLayer3Generations/dvf33-0f79744533b1316c5d92f876aaffe9d540fe315dca40c1ca4271e5ad8c1bc16d/Chunks/Chunk005", sha256 = "10302cf821e1fe10c6d62b1e7286d42687d19e0fc0941869a5c8a25633e26357" },
        { count = 200, first = "Base.MakeUp_CamoFullFace2", last = "Base.Mov_SmallTable", module = "Iris/Data/IrisLayer3Generations/dvf33-0f79744533b1316c5d92f876aaffe9d540fe315dca40c1ca4271e5ad8c1bc16d/Chunks/Chunk006", sha256 = "d24d8bf406d7e9dd14073f4317f3f221b08f88dfa6c3616f3dd4741dd3f69bb5" },
        { count = 200, first = "Base.Mov_SodaMachine", last = "Base.PillsVitamins", module = "Iris/Data/IrisLayer3Generations/dvf33-0f79744533b1316c5d92f876aaffe9d540fe315dca40c1ca4271e5ad8c1bc16d/Chunks/Chunk007", sha256 = "ec862f1e6ff6ccef28b7b65c85bc0c18ff2595b5e585e8e809027eaa40f6fec3" },
        { count = 200, first = "Base.Pineapple", last = "Base.Shirt_Bowling_White", module = "Iris/Data/IrisLayer3Generations/dvf33-0f79744533b1316c5d92f876aaffe9d540fe315dca40c1ca4271e5ad8c1bc16d/Chunks/Chunk008", sha256 = "ac10126185aed24f9adbd6a4ce7c5ffd7c71a306c029b56965d063f4d85134a7" },
        { count = 200, first = "Base.Shirt_CamoDesert", last = "Base.Tissue", module = "Iris/Data/IrisLayer3Generations/dvf33-0f79744533b1316c5d92f876aaffe9d540fe315dca40c1ca4271e5ad8c1bc16d/Chunks/Chunk009", sha256 = "217ce1d9bced4e6cd9c24296422886ba0c3c30e2143ddd672168a3b7d7e17f73" },
        { count = 200, first = "Base.Toast", last = "Base.WineInGlass", module = "Iris/Data/IrisLayer3Generations/dvf33-0f79744533b1316c5d92f876aaffe9d540fe315dca40c1ca4271e5ad8c1bc16d/Chunks/Chunk010", sha256 = "b1fed628c8d83df547370310ec2969098552148bc62df8c62ce99b175753f336" },
        { count = 105, first = "Base.WinePetrol", last = "farming.WateredCanFull", module = "Iris/Data/IrisLayer3Generations/dvf33-0f79744533b1316c5d92f876aaffe9d540fe315dca40c1ca4271e5ad8c1bc16d/Chunks/Chunk011", sha256 = "9c7130a60bd3bedcbe1e22e683af5080a25bc4aad2a56f8e24f2725807455d49" },
    },
}
