-- Auto-generated by convert_descriptions_to_lua.py
-- Routing metadata only; IrisUseCaseDescriptions remains the public facade.
-- sha256 hashes strict UTF-8 text after CRLF/CR -> LF normalization.
return {
    schema_version = "iris_usecase_chunk_range_index_v1",
    entry_count = 1631,
    chunks = {
        { count = 200, first = "Base.223Box", last = "Base.BookMetalWelding4", module = "Iris/Data/UseCaseDescriptions/Chunk001", sha256 = "422c80416abd233c6dd09a15e47d8198ec5512d601ae05b50cf11bfb2def6257" },
        { count = 200, first = "Base.BookMetalWelding5", last = "Base.Crayfish", module = "Iris/Data/UseCaseDescriptions/Chunk002", sha256 = "d49a56428605d03f721de83953fed2ddbe4a6199a3260fad6d86af5b7747f6fc" },
        { count = 200, first = "Base.Cricket", last = "Base.Hat_BaseballHelmet_Z", module = "Iris/Data/UseCaseDescriptions/Chunk003", sha256 = "113c0b2518cb6dce26e51cf2da737fc8ea693dca53b5c04a885cbc0dcdf65db1" },
        { count = 200, first = "Base.Hat_Beany", last = "Base.MakeUp_EyesShadowWhite", module = "Iris/Data/UseCaseDescriptions/Chunk004", sha256 = "6d7ced5c826a5cf694f68d1dec0d82c102b3f592c0605d9e762cefaeb4464e95" },
        { count = 200, first = "Base.MakeUp_EyesShadowYellow", last = "Base.RedDot", module = "Iris/Data/UseCaseDescriptions/Chunk005", sha256 = "f5c0879084a24572926b829b5f16cae058c6af372cd0609f3e9a538496b9880b" },
        { count = 200, first = "Base.RefriedBeans", last = "Base.SpiffoTail", module = "Iris/Data/UseCaseDescriptions/Chunk006", sha256 = "ea5eaa52bc642a1aafbdd115c72fe1ee3ea3c936077c29a5804c1396d1685533" },
        { count = 200, first = "Base.Spoon", last = "Base.WaterPotPasta", module = "Iris/Data/UseCaseDescriptions/Chunk007", sha256 = "7624d40e2ad363ef460bed8f6f01e622f4e3cc92bf4f43fbfae83a6676007683" },
        { count = 200, first = "Base.WaterPotRice", last = "farming.CabbageBagSeed", module = "Iris/Data/UseCaseDescriptions/Chunk008", sha256 = "dd325ef435f7a19bdd48f6c07d8c6c37de3bd1ee361a5536dbd7610e01540c27" },
        { count = 31, first = "farming.CabbageSeed", last = "farming.WateredCanFull", module = "Iris/Data/UseCaseDescriptions/Chunk009", sha256 = "2c135c55fe7b1b1344ee3092ee902479d02be4f5acbe7d163a953514f73124e8" },
    },
}
