-- Auto-generated by convert_descriptions_to_lua.py
-- Routing metadata only; IrisUseCaseDescriptions remains the public facade.
-- sha256 hashes strict UTF-8 text after CRLF/CR -> LF normalization.
return {
    schema_version = "iris_usecase_chunk_range_index_v1",
    entry_count = 1631,
    chunks = {
        { count = 200, first = "Base.223Box", last = "Base.BookMetalWelding4", module = "Iris/Data/UseCaseDescriptions/Chunk001", sha256 = "43245ec5ded515f8975da71b8a7fa4d813ee3cd3d01beb0d9b535f85374e39f5" },
        { count = 200, first = "Base.BookMetalWelding5", last = "Base.Crayfish", module = "Iris/Data/UseCaseDescriptions/Chunk002", sha256 = "6c095edf80e026d0638b0a1dd4700a9d57a78938fb42bf5edc67c82f42bfacb5" },
        { count = 200, first = "Base.Cricket", last = "Base.Hat_BaseballHelmet_Z", module = "Iris/Data/UseCaseDescriptions/Chunk003", sha256 = "55787a4b62b9498ba9d0975412ffe0e093d9e71aded8accf12093287061940ef" },
        { count = 200, first = "Base.Hat_Beany", last = "Base.MakeUp_EyesShadowWhite", module = "Iris/Data/UseCaseDescriptions/Chunk004", sha256 = "ab3624f1436530063719479067e05b863a137d7e91f5e4b7b5b147b7fe690567" },
        { count = 200, first = "Base.MakeUp_EyesShadowYellow", last = "Base.RedDot", module = "Iris/Data/UseCaseDescriptions/Chunk005", sha256 = "bf6d7205de090a40d9839d7c0b538b5b0c98f27a4c2ffe3c9950c4ad9071a06e" },
        { count = 200, first = "Base.RefriedBeans", last = "Base.SpiffoTail", module = "Iris/Data/UseCaseDescriptions/Chunk006", sha256 = "f9d5c5acfa0850b7c12fcf4b4fbd6c082f6161fe8283be216ac14f73bee313ff" },
        { count = 200, first = "Base.Spoon", last = "Base.WaterPotPasta", module = "Iris/Data/UseCaseDescriptions/Chunk007", sha256 = "a91c3c5bede7bfcb0bca74f9aa41f2ba22314a372f146ce6d2c54be42312fa2e" },
        { count = 200, first = "Base.WaterPotRice", last = "farming.CabbageBagSeed", module = "Iris/Data/UseCaseDescriptions/Chunk008", sha256 = "7c043be851f2ab8bc5baacdf16c614d905b76e0f4ebace47a348284b3a80b1d4" },
        { count = 31, first = "farming.CabbageSeed", last = "farming.WateredCanFull", module = "Iris/Data/UseCaseDescriptions/Chunk009", sha256 = "2143b012becc590cf57e4d7ce8c75eaa22723c459e28b5ebfcfad4d5eb28a9e4" },
    },
}
