-- Auto-generated by convert_descriptions_to_lua.py
-- Routing metadata only; IrisUseCaseDescriptions remains the public facade.
-- sha256 hashes strict UTF-8 text after CRLF/CR -> LF normalization.
return {
    schema_version = "iris_usecase_chunk_range_index_v1",
    entry_count = 1631,
    chunks = {
        { count = 200, first = "Base.223Box", last = "Base.BookMetalWelding4", module = "Iris/Data/UseCaseDescriptions/Chunk001", sha256 = "dbe3a1ace1c369b634bc0d8e1925ffdbed47236f95fd858167a4767fa66280e3" },
        { count = 200, first = "Base.BookMetalWelding5", last = "Base.Crayfish", module = "Iris/Data/UseCaseDescriptions/Chunk002", sha256 = "bbd0f5e4150a01c5638b624e0ab95f299a3f28647dda915438b481e9ae714a87" },
        { count = 200, first = "Base.Cricket", last = "Base.Hat_BaseballHelmet_Z", module = "Iris/Data/UseCaseDescriptions/Chunk003", sha256 = "8b9be23a80d1ddfa84a91bafb739a0ad494fbb220df4dc7c852cd6db8f1f0603" },
        { count = 200, first = "Base.Hat_Beany", last = "Base.MakeUp_EyesShadowWhite", module = "Iris/Data/UseCaseDescriptions/Chunk004", sha256 = "aa6b067a39a382d9000816493dccfa3a6b1208fba98ed997f40573270523554a" },
        { count = 200, first = "Base.MakeUp_EyesShadowYellow", last = "Base.RedDot", module = "Iris/Data/UseCaseDescriptions/Chunk005", sha256 = "a2ffe140685573fe8e6b58d572362c60164599ff4983193bdbed792eb317ff75" },
        { count = 200, first = "Base.RefriedBeans", last = "Base.SpiffoTail", module = "Iris/Data/UseCaseDescriptions/Chunk006", sha256 = "e62fc71041b0c6c7f2d3266e36d7074c2dbc38cfd518f55db719b4a4963d5637" },
        { count = 200, first = "Base.Spoon", last = "Base.WaterPotPasta", module = "Iris/Data/UseCaseDescriptions/Chunk007", sha256 = "7579896c26c035ca4748896f6bee1ab80140c50b2dadf96e6ad3c25cf1e062b9" },
        { count = 200, first = "Base.WaterPotRice", last = "farming.CabbageBagSeed", module = "Iris/Data/UseCaseDescriptions/Chunk008", sha256 = "da44711bc577b77d2928a991b8922b93a7c2dd881ab7820d0694d563d41422b8" },
        { count = 31, first = "farming.CabbageSeed", last = "farming.WateredCanFull", module = "Iris/Data/UseCaseDescriptions/Chunk009", sha256 = "36729ab73272a5633ce4f3af922a9d13f8419ce8dea0ac4be8bc475936c05379" },
    },
}
