-- Auto-generated by export_dvf_3_3_lua_bridge.py.
-- Do not edit manually. Rebuild from Iris/build/description/v2/output/dvf_3_3_rendered.json.

local data = {
    ["entries"] = {
        ["Base.CanOpener"] = {
            ["source"] = "composed",
            ["text_ko"] = "도구. 통조림 개봉에 쓰는 도구다. 주방과 조리 도구 보관 장소에서 발견된다.",
        },
        ["Base.ElectronicsScrap"] = {
            ["source"] = "composed",
            ["text_ko"] = "부품. 전자 조립 작업에 들어가는 부품이다. 전자기기 분해 뒤에 남는 경우가 많다.",
        },
        ["Base.GunpowderCan"] = {
            ["source"] = "composed",
            ["text_ko"] = "재료. 탄약 제작 작업에 들어가는 화약 재료다. 재장전 관련 보관함에서 발견된다.",
        },
        ["Base.ModKit"] = {
            ["source"] = "composed",
            ["text_ko"] = "도구. 총기 개조 작업에 들어가는 부품이다. 총포상과 작업대 주변에서 발견된다.",
        },
        ["Base.Tongs"] = {
            ["source"] = "composed",
            ["text_ko"] = "도구. 금속 단조에 쓰는 도구다. 대장간과 금속 작업장 주변에서 발견된다.",
        },
        ["Base.WeldingTorch"] = {
            ["source"] = "composed",
            ["text_ko"] = "도구. 금속 접합에 쓰는 도구다. 작업장과 차고에서 발견된다.",
        },
    },
    ["meta"] = {
        ["decisions_sha256"] = "7235a86c11a9e31936f0934c8dd54baa081fcf3f6208a4be35dede2e99448b9d",
        ["entries_sha256"] = "b5df554d1efbbf3ef581ada59b5fe5ad1dbcc089589911eb3d9b69b1fad34bec",
        ["facts_sha256"] = "0fbff43e932199ca36ba0c67fd683a53608ff56d0ed3373c654cdb2f67ff53e5",
        ["generated_at"] = "2026-03-27T06:02:39.464418+00:00",
        ["profiles_sha256"] = "6dea43cee3d84bf350f74d917ca95bb80318bc4fd245f27f921d4d5e689f70c5",
        ["stats"] = {
            ["active_composed"] = 6,
            ["active_override"] = 0,
            ["silent"] = 0,
            ["total"] = 6,
        },
        ["version"] = "interaction-cluster-rendered-v0",
    },
}

return data
