-- Auto-generated by export_dvf_3_3_lua_bridge.py.
-- Routing metadata only; IrisLayer3DataChunks remains the public facade.
-- sha256 hashes strict UTF-8 text after CRLF/CR -> LF normalization.
return {
    schema_version = "iris_layer3_chunk_range_index_v1",
    entry_count = 2105,
    chunks = {
        { count = 200, first = "Base.223Box", last = "Base.BookElectrician5", module = "Iris/Data/IrisLayer3Generations/dvf33-4dfbefc64ab29b5ec0a7865439a841e058346ab5fef0d4a8c276a45836a5ad07/Chunks/Chunk001", sha256 = "f7315e16cce3ee3519bad5e5c85d5b7ca10872d7c9732800eeeb3cab3565ab26" },
        { count = 200, first = "Base.BookFarming1", last = "Base.ChocoCakes", module = "Iris/Data/IrisLayer3Generations/dvf33-4dfbefc64ab29b5ec0a7865439a841e058346ab5fef0d4a8c276a45836a5ad07/Chunks/Chunk002", sha256 = "4a7b260f7dbc3bb60b4763c5e8241fc3ab39f1b8917ff1b0688dde68d4859ec9" },
        { count = 200, first = "Base.Chocolate", last = "Base.FishingNet", module = "Iris/Data/IrisLayer3Generations/dvf33-4dfbefc64ab29b5ec0a7865439a841e058346ab5fef0d4a8c276a45836a5ad07/Chunks/Chunk003", sha256 = "91ae5a03186291e7cacc40728d8c0eb3ff3b88af0bf4091c6a7001d2bcaf6862" },
        { count = 200, first = "Base.FishingRod", last = "Base.Hat_HockeyHelmet", module = "Iris/Data/IrisLayer3Generations/dvf33-4dfbefc64ab29b5ec0a7865439a841e058346ab5fef0d4a8c276a45836a5ad07/Chunks/Chunk004", sha256 = "c9ee81ef54fc7e35894470ae37ae6c528cbba63aa0f10fb337e1dac2392576b8" },
        { count = 200, first = "Base.Hat_HockeyMask", last = "Base.MakeUp_CamoFullFace1", module = "Iris/Data/IrisLayer3Generations/dvf33-4dfbefc64ab29b5ec0a7865439a841e058346ab5fef0d4a8c276a45836a5ad07/Chunks/Chunk005", sha256 = "09a1a0f976ac6e1d31ff74cc3a90090774dee74b25120bba4940524734303364" },
        { count = 200, first = "Base.MakeUp_CamoFullFace2", last = "Base.Mov_SmallTable", module = "Iris/Data/IrisLayer3Generations/dvf33-4dfbefc64ab29b5ec0a7865439a841e058346ab5fef0d4a8c276a45836a5ad07/Chunks/Chunk006", sha256 = "e9a68e6d667c956d202dc856af3dd829b323cbc24bac1230fd8ff3f413d8fe79" },
        { count = 200, first = "Base.Mov_SodaMachine", last = "Base.PillsVitamins", module = "Iris/Data/IrisLayer3Generations/dvf33-4dfbefc64ab29b5ec0a7865439a841e058346ab5fef0d4a8c276a45836a5ad07/Chunks/Chunk007", sha256 = "1a28c0068a2d93dbb9a9194d917553f054662ad8eb9afb8f9f9135f1dd29875d" },
        { count = 200, first = "Base.Pineapple", last = "Base.Shirt_Bowling_White", module = "Iris/Data/IrisLayer3Generations/dvf33-4dfbefc64ab29b5ec0a7865439a841e058346ab5fef0d4a8c276a45836a5ad07/Chunks/Chunk008", sha256 = "90dc8ecdf561421ec8e87dc8e57190d193747b7ea11e3d2d9aec8aa2fb0da935" },
        { count = 200, first = "Base.Shirt_CamoDesert", last = "Base.Tissue", module = "Iris/Data/IrisLayer3Generations/dvf33-4dfbefc64ab29b5ec0a7865439a841e058346ab5fef0d4a8c276a45836a5ad07/Chunks/Chunk009", sha256 = "a25ed746fd0727054a3c2fd03e952b9dbcfb25a1edc07aac8d56ca8a97dd3c2b" },
        { count = 200, first = "Base.Toast", last = "Base.WineInGlass", module = "Iris/Data/IrisLayer3Generations/dvf33-4dfbefc64ab29b5ec0a7865439a841e058346ab5fef0d4a8c276a45836a5ad07/Chunks/Chunk010", sha256 = "841333621f97ef1c9a57cd731cb16f803ede39a70bd9a6da0dbf7041d3390d84" },
        { count = 105, first = "Base.WinePetrol", last = "farming.WateredCanFull", module = "Iris/Data/IrisLayer3Generations/dvf33-4dfbefc64ab29b5ec0a7865439a841e058346ab5fef0d4a8c276a45836a5ad07/Chunks/Chunk011", sha256 = "329a6ef940144e64597ecf48bf4159c960bb037811e6de4542460fcf2c7217e0" },
    },
}
