-- Auto-generated by export_dvf_3_3_lua_bridge.py.
-- Routing metadata only; IrisLayer3DataChunks remains the public facade.
-- sha256 hashes strict UTF-8 text after CRLF/CR -> LF normalization.
return {
    schema_version = "iris_layer3_chunk_range_index_v1",
    entry_count = 2105,
    chunks = {
        { count = 200, first = "Base.223Box", last = "Base.BookElectrician5", module = "Iris/Data/IrisLayer3Generations/dvf33-05d76b51c5e1058be4d79afd8a43bc2f0ac8a11c136523166770f181eeaf82c1/Chunks/Chunk001", sha256 = "0ac63e2a85b37bbf28fa4448afc2d97a204e5fab9c4325b2d816abd79e2144a0" },
        { count = 200, first = "Base.BookFarming1", last = "Base.ChocoCakes", module = "Iris/Data/IrisLayer3Generations/dvf33-05d76b51c5e1058be4d79afd8a43bc2f0ac8a11c136523166770f181eeaf82c1/Chunks/Chunk002", sha256 = "095bd457497756a73f92dc5c1ff617ba7534de03653af71dfaedb048fb147b62" },
        { count = 200, first = "Base.Chocolate", last = "Base.FishingNet", module = "Iris/Data/IrisLayer3Generations/dvf33-05d76b51c5e1058be4d79afd8a43bc2f0ac8a11c136523166770f181eeaf82c1/Chunks/Chunk003", sha256 = "4c4ef642f72a5b5089a7f38e850ef076aeacc849a4a16a74a50a820875bef604" },
        { count = 200, first = "Base.FishingRod", last = "Base.Hat_HockeyHelmet", module = "Iris/Data/IrisLayer3Generations/dvf33-05d76b51c5e1058be4d79afd8a43bc2f0ac8a11c136523166770f181eeaf82c1/Chunks/Chunk004", sha256 = "6e835aa920d4c73d9bff941e039067167a50ad59d4cc9dfbdc72689f9de90cea" },
        { count = 200, first = "Base.Hat_HockeyMask", last = "Base.MakeUp_CamoFullFace1", module = "Iris/Data/IrisLayer3Generations/dvf33-05d76b51c5e1058be4d79afd8a43bc2f0ac8a11c136523166770f181eeaf82c1/Chunks/Chunk005", sha256 = "dcd48db02150dd683f24bdd9d7cefcb92a4b0fc0acb2cbd2e43d927469cfc4af" },
        { count = 200, first = "Base.MakeUp_CamoFullFace2", last = "Base.Mov_SmallTable", module = "Iris/Data/IrisLayer3Generations/dvf33-05d76b51c5e1058be4d79afd8a43bc2f0ac8a11c136523166770f181eeaf82c1/Chunks/Chunk006", sha256 = "f2f5f01b75475904bd46b6bced3ac5aa9ef39d30801948a776bd5f73ade29677" },
        { count = 200, first = "Base.Mov_SodaMachine", last = "Base.PillsVitamins", module = "Iris/Data/IrisLayer3Generations/dvf33-05d76b51c5e1058be4d79afd8a43bc2f0ac8a11c136523166770f181eeaf82c1/Chunks/Chunk007", sha256 = "e78815bfd2fef4b6acf94542b19e2ae777ea67aeb608656a5138c1f2cad2c4d2" },
        { count = 200, first = "Base.Pineapple", last = "Base.Shirt_Bowling_White", module = "Iris/Data/IrisLayer3Generations/dvf33-05d76b51c5e1058be4d79afd8a43bc2f0ac8a11c136523166770f181eeaf82c1/Chunks/Chunk008", sha256 = "42b8bfb97f67db14575bedb78e1a6de1d64369521aaaa3193bb0239ee86a52ef" },
        { count = 200, first = "Base.Shirt_CamoDesert", last = "Base.Tissue", module = "Iris/Data/IrisLayer3Generations/dvf33-05d76b51c5e1058be4d79afd8a43bc2f0ac8a11c136523166770f181eeaf82c1/Chunks/Chunk009", sha256 = "699ede5612a8cbecbf7f66f72853752ae9746564e42c560ae5889df902150848" },
        { count = 200, first = "Base.Toast", last = "Base.WineInGlass", module = "Iris/Data/IrisLayer3Generations/dvf33-05d76b51c5e1058be4d79afd8a43bc2f0ac8a11c136523166770f181eeaf82c1/Chunks/Chunk010", sha256 = "a9eca99aa9baa3cf5e3b7043e423d6a1806d6c82cb8f7fd44cae62386c4badb2" },
        { count = 105, first = "Base.WinePetrol", last = "farming.WateredCanFull", module = "Iris/Data/IrisLayer3Generations/dvf33-05d76b51c5e1058be4d79afd8a43bc2f0ac8a11c136523166770f181eeaf82c1/Chunks/Chunk011", sha256 = "eede7fdb2104817217df1dc67938691335d882054fd5cd626904d116e0d9e165" },
    },
}
