-- Auto-generated by export_dvf_3_3_lua_bridge.py.
-- Routing metadata only; IrisLayer3DataChunks remains the public facade.
-- sha256 hashes strict UTF-8 text after CRLF/CR -> LF normalization.
return {
    schema_version = "iris_layer3_chunk_range_index_v1",
    entry_count = 2105,
    chunks = {
        { count = 200, first = "Base.223Box", last = "Base.BookElectrician5", module = "Iris/Data/IrisLayer3Generations/dvf33-96b216c3a79fbbb6855f6aac3d49dbad5acbfc73c65c6a19fb3e580e7c9e448c/Chunks/Chunk001", sha256 = "4d3e0b11aa3f80ea7f532258d65483aba1eeb81783e7c87dba3c75945951fb99" },
        { count = 200, first = "Base.BookFarming1", last = "Base.ChocoCakes", module = "Iris/Data/IrisLayer3Generations/dvf33-96b216c3a79fbbb6855f6aac3d49dbad5acbfc73c65c6a19fb3e580e7c9e448c/Chunks/Chunk002", sha256 = "5ecc0c6f9f54957ad70d07677199d8bb5cf2aec85a18ae641488766a89ed100d" },
        { count = 200, first = "Base.Chocolate", last = "Base.FishingNet", module = "Iris/Data/IrisLayer3Generations/dvf33-96b216c3a79fbbb6855f6aac3d49dbad5acbfc73c65c6a19fb3e580e7c9e448c/Chunks/Chunk003", sha256 = "465166eac37af1ac783060d290502ffa23a04d6b86cf86b22042f7821c1f14e0" },
        { count = 200, first = "Base.FishingRod", last = "Base.Hat_HockeyHelmet", module = "Iris/Data/IrisLayer3Generations/dvf33-96b216c3a79fbbb6855f6aac3d49dbad5acbfc73c65c6a19fb3e580e7c9e448c/Chunks/Chunk004", sha256 = "bcd4b0ae1901fc815490ddc7e61f5e2c6c89439c10d2b3897e22eb3c12f98b07" },
        { count = 200, first = "Base.Hat_HockeyMask", last = "Base.MakeUp_CamoFullFace1", module = "Iris/Data/IrisLayer3Generations/dvf33-96b216c3a79fbbb6855f6aac3d49dbad5acbfc73c65c6a19fb3e580e7c9e448c/Chunks/Chunk005", sha256 = "fc1ad48ff4a74bff03ce3b85d6b3bef1980f8007c65e1b4b43d38272591cace7" },
        { count = 200, first = "Base.MakeUp_CamoFullFace2", last = "Base.Mov_SmallTable", module = "Iris/Data/IrisLayer3Generations/dvf33-96b216c3a79fbbb6855f6aac3d49dbad5acbfc73c65c6a19fb3e580e7c9e448c/Chunks/Chunk006", sha256 = "79af2c190eee2990d404969cadaebc2fa8b9f2eb17584c522c090fbc03b4e57b" },
        { count = 200, first = "Base.Mov_SodaMachine", last = "Base.PillsVitamins", module = "Iris/Data/IrisLayer3Generations/dvf33-96b216c3a79fbbb6855f6aac3d49dbad5acbfc73c65c6a19fb3e580e7c9e448c/Chunks/Chunk007", sha256 = "a8bba3438bf43ff9ed3f575d53f85d46a44fd743e352aa73e53bc9729f9a8cdd" },
        { count = 200, first = "Base.Pineapple", last = "Base.Shirt_Bowling_White", module = "Iris/Data/IrisLayer3Generations/dvf33-96b216c3a79fbbb6855f6aac3d49dbad5acbfc73c65c6a19fb3e580e7c9e448c/Chunks/Chunk008", sha256 = "ffdc57d774dc627ceacef4bbd04851f743ea4aaead66cf9fa77ab6b3e8fa997a" },
        { count = 200, first = "Base.Shirt_CamoDesert", last = "Base.Tissue", module = "Iris/Data/IrisLayer3Generations/dvf33-96b216c3a79fbbb6855f6aac3d49dbad5acbfc73c65c6a19fb3e580e7c9e448c/Chunks/Chunk009", sha256 = "e837261be0fbbdb275fd89f32039c7b933578e9da98af19e6650196a0c277f9b" },
        { count = 200, first = "Base.Toast", last = "Base.WineInGlass", module = "Iris/Data/IrisLayer3Generations/dvf33-96b216c3a79fbbb6855f6aac3d49dbad5acbfc73c65c6a19fb3e580e7c9e448c/Chunks/Chunk010", sha256 = "e5a74119caff3a8f41473347ec3e561dfeb626f37201752a902a696be8ade3f0" },
        { count = 105, first = "Base.WinePetrol", last = "farming.WateredCanFull", module = "Iris/Data/IrisLayer3Generations/dvf33-96b216c3a79fbbb6855f6aac3d49dbad5acbfc73c65c6a19fb3e580e7c9e448c/Chunks/Chunk011", sha256 = "91d7acde2766d5e876b11ae090cde502ef186daf591ffc2eb0a30f380d6e1d5b" },
    },
}
