"""
IrisCapabilities.lua 생성 스크립트
capability_by_fulltype.json → IrisCapabilities.lua 변환
"""

import json
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent.resolve()
IRIS_DIR = SCRIPT_DIR.parent.parent  # evidence/rightclick → Iris
INPUT_FILE = IRIS_DIR / "output" / "capability_by_fulltype.json"
OUTPUT_FILE = IRIS_DIR / "media" / "lua" / "client" / "Iris" / "Data" / "IrisCapabilities.lua"


def generate_lua():
    # JSON 로드
    with open(INPUT_FILE, "r", encoding="utf-8") as f:
        data = json.load(f)
    
    # Lua 생성
    lua_lines = [
        "-- Iris Right-Click Capabilities Data",
        "-- Auto-generated by rightclick pipeline",
        f"-- Total items: {len(data)}",
        "",
        "local IrisCapabilities = {}",
        "",
    ]
    
    for fulltype, caps in sorted(data.items()):
        caps_str = ", ".join(f'"{c}"' for c in caps)
        lua_lines.append(f'IrisCapabilities["{fulltype}"] = {{ {caps_str} }}')
    
    lua_lines.append("")
    lua_lines.append("return IrisCapabilities")
    lua_lines.append("")
    
    # 저장
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(lua_lines))
    
    print(f"[OK] Generated IrisCapabilities.lua with {len(data)} entries")


if __name__ == "__main__":
    generate_lua()
