-- Iris Recipe Index Data
-- Auto-generated by build_iris_recipe_index_data.py
-- DO NOT EDIT MANUALLY

local IrisRecipeIndexData = {}

IrisRecipeIndexData.version = "v2.4"
IrisRecipeIndexData.itemRoles = {
    ["Base.223Box"] = {
        { role = "input", category = "Unknown", recipe = "Open Box of .223 Ammo" },
    },
    ["Base.223Bullets"] = {
        { role = "input", category = "Unknown", recipe = "Gather Gunpowder" },
        { role = "input", category = "Unknown", recipe = "Place .223 Ammo in Box" },
    },
    ["Base.223BulletsMold"] = {
        { role = "keep", category = "Smithing", recipe = "Make 223 Bullets" },
    },
    ["Base.308Box"] = {
        { role = "input", category = "Unknown", recipe = "Open Box of .308 Ammo" },
    },
    ["Base.308Bullets"] = {
        { role = "input", category = "Unknown", recipe = "Gather Gunpowder" },
        { role = "input", category = "Unknown", recipe = "Place .308 Ammo in Box" },
    },
    ["Base.308BulletsMold"] = {
        { role = "keep", category = "Smithing", recipe = "Make 308 Bullets" },
    },
    ["Base.556Box"] = {
        { role = "input", category = "Unknown", recipe = "Open Box of .556 Ammo" },
    },
    ["Base.556Bullets"] = {
        { role = "input", category = "Unknown", recipe = "Gather Gunpowder" },
        { role = "input", category = "Unknown", recipe = "Place .556 Ammo in Box" },
    },
    ["Base.9mmBulletsMold"] = {
        { role = "keep", category = "Smithing", recipe = "Make 9mm Bullets" },
    },
    ["Base.Aerosolbomb"] = {
        { role = "input", category = "Electrical", recipe = "Add Crafted Trigger" },
        { role = "input", category = "Electrical", recipe = "Add Motion Sensor V1" },
        { role = "input", category = "Electrical", recipe = "Add Motion Sensor V2" },
        { role = "input", category = "Electrical", recipe = "Add Motion Sensor V3" },
        { role = "input", category = "Electrical", recipe = "Add Timer" },
    },
    ["Base.AlarmClock2"] = {
        { role = "input", category = "Electrical", recipe = "Make Timer" },
    },
    ["Base.Aluminum"] = {
        { role = "input", category = "Electrical", recipe = "Craft Makeshift HAM Radio" },
        { role = "input", category = "Electrical", recipe = "Craft Makeshift Radio" },
        { role = "input", category = "Electrical", recipe = "Craft Makeshift Walkie Talkie" },
        { role = "input", category = "Engineer", recipe = "Make Aerosol bomb" },
        { role = "input", category = "Unknown", recipe = "Make Tin Foil Hat" },
    },
    ["Base.Amplifier"] = {
        { role = "input", category = "Electrical", recipe = "Craft Makeshift HAM Radio" },
        { role = "input", category = "Electrical", recipe = "Craft Makeshift Radio" },
        { role = "input", category = "Electrical", recipe = "Craft Makeshift Walkie Talkie" },
        { role = "input", category = "Electrical", recipe = "Make Noise Maker" },
    },
    ["Base.Avocado"] = {
        { role = "input", category = "Cooking", recipe = "Make Maki" },
        { role = "input", category = "Cooking", recipe = "Make Onigiri" },
    },
    ["Base.Axe"] = {
        { role = "keep", category = "Cooking", recipe = "Slice Watermelon" },
    },
    ["Base.AxeStone"] = {
        { role = "keep", category = "Cooking", recipe = "Slice Watermelon" },
    },
    ["Base.BakingPan"] = {
        { role = "input", category = "Cooking", recipe = "Place Cake in Baking Pan" },
        { role = "input", category = "Cooking", recipe = "Place Pie in Baking Pan" },
    },
    ["Base.BakingSoda"] = {
        { role = "input", category = "Cooking", recipe = "Make Biscuits" },
        { role = "input", category = "Cooking", recipe = "Make Chocolate Chip Cookie Dough" },
        { role = "input", category = "Cooking", recipe = "Make Chocolate Cookie Dough" },
        { role = "input", category = "Cooking", recipe = "Make Fried Onion Rings" },
        { role = "input", category = "Cooking", recipe = "Make Fried Shrimp" },
        { role = "input", category = "Cooking", recipe = "Make Oatmeal Cookie Dough" },
        { role = "input", category = "Cooking", recipe = "Make Sugar Cookie Dough" },
    },
    ["Base.BakingTray"] = {
        { role = "input", category = "Cooking", recipe = "Make Chocolate Chip Cookie Dough" },
        { role = "input", category = "Cooking", recipe = "Make Chocolate Cookie Dough" },
        { role = "input", category = "Cooking", recipe = "Make Oatmeal Cookie Dough" },
        { role = "input", category = "Cooking", recipe = "Make Shortbread Cookie Dough" },
        { role = "input", category = "Cooking", recipe = "Make Sugar Cookie Dough" },
    },
    ["Base.BakingTray_Muffin"] = {
        { role = "input", category = "Cooking", recipe = "Clean Tray" },
        { role = "input", category = "Cooking", recipe = "Get 6 Muffins" },
    },
    ["Base.BakingTray_Muffin_Recipe"] = {
        { role = "input", category = "Cooking", recipe = "Clean Tray" },
        { role = "input", category = "Cooking", recipe = "Get 6 Muffins" },
    },
    ["Base.BallPeenHammer"] = {
        { role = "keep", category = "Smithing", recipe = "Make 223 Bullets Mold" },
        { role = "keep", category = "Smithing", recipe = "Make 308 Bullets Mold" },
        { role = "keep", category = "Smithing", recipe = "Make 9mm Bullets Mold" },
        { role = "keep", category = "Smithing", recipe = "Make Axe" },
        { role = "keep", category = "Smithing", recipe = "Make Baking Pan" },
        { role = "keep", category = "Smithing", recipe = "Make Baking Tray" },
        { role = "keep", category = "Smithing", recipe = "Make Cooking Pot" },
        { role = "keep", category = "Smithing", recipe = "Make Crowbar" },
        { role = "keep", category = "Smithing", recipe = "Make Door Knob" },
        { role = "keep", category = "Smithing", recipe = "Make Golfclub" },
        { role = "keep", category = "Smithing", recipe = "Make Hammer" },
        { role = "keep", category = "Smithing", recipe = "Make Hinge" },
        { role = "keep", category = "Smithing", recipe = "Make Hunting Knife" },
        { role = "keep", category = "Smithing", recipe = "Make Kitchen Knife" },
        { role = "keep", category = "Smithing", recipe = "Make Letter Opener" },
        { role = "keep", category = "Smithing", recipe = "Make Metal Drum" },
        { role = "keep", category = "Smithing", recipe = "Make Pan" },
        { role = "keep", category = "Smithing", recipe = "Make Roasting Pan" },
        { role = "keep", category = "Smithing", recipe = "Make Saucepan" },
        { role = "keep", category = "Smithing", recipe = "Make Saw" },
        { role = "keep", category = "Smithing", recipe = "Make Scissors" },
        { role = "keep", category = "Smithing", recipe = "Make Sheet Metal" },
        { role = "keep", category = "Smithing", recipe = "Make Shotgun Shells Mold" },
        { role = "keep", category = "Smithing", recipe = "Make Sledgehammer" },
        { role = "keep", category = "Smithing", recipe = "Make Suture Needle" },
        { role = "keep", category = "Smithing", recipe = "Make Suture Needle Holder" },
        { role = "keep", category = "Smithing", recipe = "Make Tweezers" },
    },
    ["Base.Baloney"] = {
        { role = "input", category = "Cooking", recipe = "Slice Baloney" },
    },
    ["Base.Bandage"] = {
        { role = "input", category = "Health", recipe = "Disinfect Bandage" },
    },
    ["Base.BandageDirty"] = {
        { role = "input", category = "Health", recipe = "Clean Bandage" },
    },
    ["Base.BaseballBat"] = {
        { role = "input", category = "Carpentry", recipe = "Build Spiked Baseball Bat" },
        { role = "keep", category = "Cooking", recipe = "Smash Watermelon" },
    },
    ["Base.BaseballBatNails"] = {
        { role = "keep", category = "Cooking", recipe = "Smash Watermelon" },
    },
    ["Base.Bass"] = {
        { role = "input", category = "Cooking", recipe = "Slice Fillet" },
    },
    ["Base.Battery"] = {
        { role = "input", category = "Unknown", recipe = "Insert Battery into Duck" },
        { role = "input", category = "Unknown", recipe = "Insert Battery into Flashlight" },
    },
    ["Base.BeerEmpty"] = {
        { role = "input", category = "Unknown", recipe = "Make Molotov Cocktail" },
        { role = "input", category = "Unknown", recipe = "Smash Bottle" },
    },
    ["Base.BellPepper"] = {
        { role = "input", category = "Cooking", recipe = "Make Jar of Bell Peppers" },
    },
    ["Base.BlowTorch"] = {
        { role = "input", category = "Welding", recipe = "Make Metal Bar" },
        { role = "input", category = "Welding", recipe = "Make Metal Pipe" },
        { role = "input", category = "Welding", recipe = "Make Metal Sheet" },
        { role = "input", category = "Welding", recipe = "Make Small Metal Sheet" },
        { role = "input", category = "Welding", recipe = "Refill Blow Torch" },
    },
    ["Base.Book"] = {
        { role = "input", category = "Survivalist", recipe = "Make Campfire Kit" },
    },
    ["Base.Bowl"] = {
        { role = "input", category = "Cooking", recipe = "Make 2 Bowls of Pasta" },
        { role = "input", category = "Cooking", recipe = "Make 2 Bowls of Rice" },
        { role = "input", category = "Cooking", recipe = "Make 2 Bowls of Soup" },
        { role = "input", category = "Cooking", recipe = "Make 2 Bowls of Stew" },
        { role = "input", category = "Cooking", recipe = "Make 4 Bowls of Pasta" },
        { role = "input", category = "Cooking", recipe = "Make 4 Bowls of Rice" },
        { role = "input", category = "Cooking", recipe = "Make 4 Bowls of Soup" },
        { role = "input", category = "Cooking", recipe = "Make 4 Bowls of Stew" },
        { role = "keep", category = "Cooking", recipe = "Make Biscuits" },
        { role = "input", category = "Cooking", recipe = "Make Bowl of Beans" },
        { role = "input", category = "Cooking", recipe = "Make Bowl of Cereal" },
        { role = "input", category = "Cooking", recipe = "Make Bowl of Oatmeal" },
        { role = "keep", category = "Cooking", recipe = "Make Bread Dough" },
        { role = "input", category = "Cooking", recipe = "Make Cake Batter" },
        { role = "keep", category = "Cooking", recipe = "Make Chocolate Chip Cookie Dough" },
        { role = "keep", category = "Cooking", recipe = "Make Chocolate Cookie Dough" },
        { role = "keep", category = "Cooking", recipe = "Make Gravy" },
        { role = "keep", category = "Cooking", recipe = "Make Oatmeal Cookie Dough" },
        { role = "keep", category = "Cooking", recipe = "Make Pancake" },
        { role = "keep", category = "Cooking", recipe = "Make Pie Dough" },
        { role = "keep", category = "Cooking", recipe = "Make Pizza" },
        { role = "keep", category = "Cooking", recipe = "Make Shortbread Cookie Dough" },
        { role = "keep", category = "Cooking", recipe = "Make Sugar Cookie Dough" },
        { role = "keep", category = "Cooking", recipe = "Prepare Muffins" },
    },
    ["Base.BoxOfJars"] = {
        { role = "input", category = "Unknown", recipe = "Open Box of Jars" },
    },
    ["Base.Bread"] = {
        { role = "input", category = "Cooking", recipe = "Slice Bread" },
    },
    ["Base.BreadDough"] = {
        { role = "input", category = "Cooking", recipe = "Slice Bread" },
    },
    ["Base.BreadKnife"] = {
        { role = "input", category = "Survivalist", recipe = "Attach Bread Knife to Spear" },
    },
    ["Base.BreadSlices"] = {
        { role = "input", category = "Cooking", recipe = "Make Cheese Sandwich" },
    },
    ["Base.Broccoli"] = {
        { role = "input", category = "Cooking", recipe = "Make Jar of Broccoli" },
    },
    ["Base.BrokenFishingNet"] = {
        { role = "input", category = "Fishing", recipe = "Get Wire Back" },
    },
    ["Base.BucketEmpty"] = {
        { role = "input", category = "Carpentry", recipe = "Make Bucket of Plaster" },
    },
    ["Base.BucketWaterFull"] = {
        { role = "input", category = "Carpentry", recipe = "Make Bucket of Plaster" },
    },
    ["Base.Bullets38"] = {
        { role = "input", category = "Unknown", recipe = "Gather Gunpowder" },
        { role = "input", category = "Unknown", recipe = "Place .38 Speciam Bullets in Box" },
    },
    ["Base.Bullets38Box"] = {
        { role = "input", category = "Unknown", recipe = "Open Box of .38 Special Bullets" },
    },
    ["Base.Bullets44"] = {
        { role = "input", category = "Unknown", recipe = "Gather Gunpowder" },
        { role = "input", category = "Unknown", recipe = "Place .44 Magnum Bullets in Box" },
    },
    ["Base.Bullets44Box"] = {
        { role = "input", category = "Unknown", recipe = "Open Box of .44 Magnum Bullets" },
    },
    ["Base.Bullets45"] = {
        { role = "input", category = "Unknown", recipe = "Gather Gunpowder" },
        { role = "input", category = "Unknown", recipe = "Place .45 Auto Bullets in Box" },
    },
    ["Base.Bullets45Box"] = {
        { role = "input", category = "Unknown", recipe = "Open Box of .45 Auto Bullets" },
    },
    ["Base.Bullets9mm"] = {
        { role = "input", category = "Unknown", recipe = "Gather Gunpowder" },
        { role = "input", category = "Unknown", recipe = "Place 9mm Bullets in Box" },
    },
    ["Base.Bullets9mmBox"] = {
        { role = "input", category = "Unknown", recipe = "Open Box of 9mm Bullets" },
    },
    ["Base.Butter"] = {
        { role = "input", category = "Cooking", recipe = "Make Pie Dough" },
        { role = "input", category = "Cooking", recipe = "Make Shortbread Cookie Dough" },
    },
    ["Base.ButterKnife"] = {
        { role = "input", category = "Survivalist", recipe = "Attach Butter Knife to Spear" },
    },
    ["Base.CakeBatter"] = {
        { role = "input", category = "Cooking", recipe = "Place Cake in Baking Pan" },
    },
    ["Base.CakeRaw"] = {
        { role = "input", category = "Cooking", recipe = "Slice Cake" },
    },
    ["Base.Candle"] = {
        { role = "input", category = "Unknown", recipe = "Light Candle" },
    },
    ["Base.CandleLit"] = {
        { role = "input", category = "Unknown", recipe = "Extinguish Candle" },
    },
    ["Base.CandyPackage"] = {
        { role = "input", category = "Cooking", recipe = "Open Candy Package" },
    },
    ["Base.CannedBellPepper"] = {
        { role = "input", category = "Cooking", recipe = "Open Jar of Bell Peppers" },
    },
    ["Base.CannedBolognese"] = {
        { role = "input", category = "Cooking", recipe = "Open Canned Bolognese" },
    },
    ["Base.CannedBroccoli"] = {
        { role = "input", category = "Cooking", recipe = "Open Jar of Broccoli" },
    },
    ["Base.CannedCabbage"] = {
        { role = "input", category = "Cooking", recipe = "Open Jar of Cabbage" },
    },
    ["Base.CannedCarrots"] = {
        { role = "input", category = "Cooking", recipe = "Open Jar of Carrots" },
    },
    ["Base.CannedCarrots2"] = {
        { role = "input", category = "Cooking", recipe = "Open Canned Carrots" },
    },
    ["Base.CannedChili"] = {
        { role = "input", category = "Cooking", recipe = "Open Canned Chili" },
    },
    ["Base.CannedCorn"] = {
        { role = "input", category = "Cooking", recipe = "Open Canned Corn" },
    },
    ["Base.CannedCornedBeef"] = {
        { role = "input", category = "Cooking", recipe = "Open Canned Corned Beef" },
    },
    ["Base.CannedEggplant"] = {
        { role = "input", category = "Cooking", recipe = "Open Jar of Eggplants" },
    },
    ["Base.CannedFruitBeverage"] = {
        { role = "input", category = "Cooking", recipe = "Open Canned Fruit Beverage" },
    },
    ["Base.CannedFruitCocktail"] = {
        { role = "input", category = "Cooking", recipe = "Open Canned Fruit Cocktail" },
    },
    ["Base.CannedLeek"] = {
        { role = "input", category = "Cooking", recipe = "Open Jar of Leeks" },
    },
    ["Base.CannedMilk"] = {
        { role = "input", category = "Cooking", recipe = "Open Condensed Milk" },
    },
    ["Base.CannedMushroomSoup"] = {
        { role = "input", category = "Cooking", recipe = "Make Pot of Soup" },
        { role = "input", category = "Cooking", recipe = "Open Canned Mushroom Soup" },
    },
    ["Base.CannedMushroomSoupOpen"] = {
        { role = "input", category = "Cooking", recipe = "Make Pot of Soup" },
    },
    ["Base.CannedPeaches"] = {
        { role = "input", category = "Cooking", recipe = "Open Canned Peaches" },
    },
    ["Base.CannedPeas"] = {
        { role = "input", category = "Cooking", recipe = "Open Canned Peas" },
    },
    ["Base.CannedPineapple"] = {
        { role = "input", category = "Cooking", recipe = "Open Canned Pineapple" },
    },
    ["Base.CannedPotato"] = {
        { role = "input", category = "Cooking", recipe = "Open Jar of Potatoes" },
    },
    ["Base.CannedPotato2"] = {
        { role = "input", category = "Cooking", recipe = "Open Canned Potato" },
    },
    ["Base.CannedRedRadish"] = {
        { role = "input", category = "Cooking", recipe = "Open Jar of Red Radishes" },
    },
    ["Base.CannedSardines"] = {
        { role = "input", category = "Cooking", recipe = "Open Canned Sardines" },
    },
    ["Base.CannedTomato"] = {
        { role = "input", category = "Cooking", recipe = "Open Jar of Tomatoes" },
    },
    ["Base.CannedTomato2"] = {
        { role = "input", category = "Cooking", recipe = "Open Canned Tomato" },
    },
    ["Base.Carrots"] = {
        { role = "input", category = "Cooking", recipe = "Make Jar of Carrots" },
    },
    ["Base.Catfish"] = {
        { role = "input", category = "Cooking", recipe = "Slice Fillet" },
    },
    ["Base.Cereal"] = {
        { role = "input", category = "Cooking", recipe = "Make Bowl of Cereal" },
    },
    ["Base.Cheese"] = {
        { role = "input", category = "Cooking", recipe = "Make Pizza" },
    },
    ["Base.ChocolateChips"] = {
        { role = "input", category = "Cooking", recipe = "Make Chocolate Chip Cookie Dough" },
    },
    ["Base.Cigarettes"] = {
        { role = "input", category = "Farming", recipe = "Make Flies Cure" },
    },
    ["Base.ClosedUmbrellaBlack"] = {
        { role = "input", category = "Unknown", recipe = "Open Umbrella" },
    },
    ["Base.ClosedUmbrellaBlue"] = {
        { role = "input", category = "Unknown", recipe = "Open Umbrella" },
    },
    ["Base.ClosedUmbrellaRed"] = {
        { role = "input", category = "Unknown", recipe = "Open Umbrella" },
    },
    ["Base.ClosedUmbrellaWhite"] = {
        { role = "input", category = "Unknown", recipe = "Open Umbrella" },
    },
    ["Base.CocoaPowder"] = {
        { role = "input", category = "Cooking", recipe = "Make Chocolate Cookie Dough" },
    },
    ["Base.Coldpack"] = {
        { role = "input", category = "Engineer", recipe = "Make Smoke Bomb" },
    },
    ["Base.Comfrey"] = {
        { role = "input", category = "Health", recipe = "Make Comfrey Poultice" },
    },
    ["Base.Cone"] = {
        { role = "input", category = "Cooking", recipe = "Scoop Ice Cream" },
    },
    ["Base.CookieChocolateChipDough"] = {
        { role = "input", category = "Cooking", recipe = "Empty Baking Tray" },
        { role = "input", category = "Cooking", recipe = "Get 6 Cookies" },
    },
    ["Base.CookiesChocolateDough"] = {
        { role = "input", category = "Cooking", recipe = "Empty Baking Tray" },
        { role = "input", category = "Cooking", recipe = "Get 6 Cookies" },
    },
    ["Base.CookiesOatmealDough"] = {
        { role = "input", category = "Cooking", recipe = "Empty Baking Tray" },
        { role = "input", category = "Cooking", recipe = "Get 6 Cookies" },
    },
    ["Base.CookiesShortbreadDough"] = {
        { role = "input", category = "Cooking", recipe = "Empty Baking Tray" },
        { role = "input", category = "Cooking", recipe = "Get 6 Cookies" },
    },
    ["Base.CookiesSugarDough"] = {
        { role = "input", category = "Cooking", recipe = "Empty Baking Tray" },
        { role = "input", category = "Cooking", recipe = "Get 6 Cookies" },
    },
    ["Base.CordlessPhone"] = {
        { role = "input", category = "Electrical", recipe = "Dismantle Cordless Phone" },
    },
    ["Base.CottonBalls"] = {
        { role = "input", category = "Health", recipe = "Douse Cotton in Alcohol" },
        { role = "input", category = "Health", recipe = "Put Alcohol on Cotton" },
    },
    ["Base.Crappie"] = {
        { role = "input", category = "Cooking", recipe = "Slice Fillet" },
    },
    ["Base.DeadBird"] = {
        { role = "input", category = "Cooking", recipe = "Butcher Bird" },
    },
    ["Base.DeadMouse"] = {
        { role = "input", category = "Cooking", recipe = "Butcher Small Animal" },
    },
    ["Base.DeadRabbit"] = {
        { role = "input", category = "Cooking", recipe = "Butcher Rabbit" },
    },
    ["Base.DeadRat"] = {
        { role = "input", category = "Cooking", recipe = "Butcher Small Animal" },
    },
    ["Base.DeadSquirrel"] = {
        { role = "input", category = "Cooking", recipe = "Butcher Small Animal" },
    },
    ["Base.DenimStrips"] = {
        { role = "input", category = "Engineer", recipe = "Make Flame bomb" },
        { role = "input", category = "Unknown", recipe = "Make Molotov Cocktail" },
        { role = "input", category = "Health", recipe = "Make Splint" },
        { role = "input", category = "Survivalist", recipe = "Make Stone Axe" },
        { role = "input", category = "Survivalist", recipe = "Make Stone Hammer" },
        { role = "input", category = "Survivalist", recipe = "Make Stone Knife" },
    },
    ["Base.DenimStripsDirty"] = {
        { role = "input", category = "Health", recipe = "Clean Denim Strips" },
        { role = "input", category = "Engineer", recipe = "Make Flame bomb" },
        { role = "input", category = "Unknown", recipe = "Make Molotov Cocktail" },
        { role = "input", category = "Health", recipe = "Make Splint" },
        { role = "input", category = "Survivalist", recipe = "Make Stone Axe" },
        { role = "input", category = "Survivalist", recipe = "Make Stone Hammer" },
        { role = "input", category = "Survivalist", recipe = "Make Stone Knife" },
    },
    ["Base.Dogfood"] = {
        { role = "input", category = "Cooking", recipe = "Open Dog Food" },
    },
    ["Base.Doorknob"] = {
        { role = "input", category = "Carpentry", recipe = "Build Drawer" },
    },
    ["Base.DoubleBarrelShotgun"] = {
        { role = "input", category = "Unknown", recipe = "Saw Off Double Barrel Shotgun" },
    },
    ["Base.DuctTape"] = {
        { role = "input", category = "Electrical", recipe = "Add Crafted Trigger" },
        { role = "input", category = "Electrical", recipe = "Add Motion Sensor V1" },
        { role = "input", category = "Electrical", recipe = "Add Motion Sensor V2" },
        { role = "input", category = "Electrical", recipe = "Add Motion Sensor V3" },
        { role = "input", category = "Electrical", recipe = "Add Timer" },
        { role = "input", category = "Survivalist", recipe = "Attach Bread Knife to Spear" },
        { role = "input", category = "Survivalist", recipe = "Attach Butter Knife to Spear" },
        { role = "input", category = "Survivalist", recipe = "Attach Fork to Spear" },
        { role = "input", category = "Survivalist", recipe = "Attach Hand Fork to Spear" },
        { role = "input", category = "Survivalist", recipe = "Attach Hunting Knife to Spear" },
        { role = "input", category = "Survivalist", recipe = "Attach Ice Pick to Spear" },
        { role = "input", category = "Survivalist", recipe = "Attach Kitchen Knife to Spear" },
        { role = "input", category = "Survivalist", recipe = "Attach Letter Opener to Spear" },
        { role = "input", category = "Survivalist", recipe = "Attach Machete to Spear" },
        { role = "input", category = "Survivalist", recipe = "Attach Scalpel to Spear" },
        { role = "input", category = "Survivalist", recipe = "Attach Scissors to Spear" },
        { role = "input", category = "Survivalist", recipe = "Attach Screwdriver to Spear" },
        { role = "input", category = "Survivalist", recipe = "Attach Spoon to Spear" },
    },
    ["Base.Earbuds"] = {
        { role = "input", category = "Electrical", recipe = "Dismantle Earbuds" },
    },
    ["Base.Egg"] = {
        { role = "input", category = "Cooking", recipe = "Put Eggs in Carton" },
    },
    ["Base.EggCarton"] = {
        { role = "input", category = "Cooking", recipe = "Open Egg Carton" },
    },
    ["Base.Eggplant"] = {
        { role = "input", category = "Cooking", recipe = "Make Jar of Eggplants" },
    },
    ["Base.ElectronicsScrap"] = {
        { role = "input", category = "Electrical", recipe = "Add Crafted Trigger" },
        { role = "input", category = "Electrical", recipe = "Add Motion Sensor V1" },
        { role = "input", category = "Electrical", recipe = "Add Motion Sensor V2" },
        { role = "input", category = "Electrical", recipe = "Add Motion Sensor V3" },
        { role = "input", category = "Electrical", recipe = "Add Timer" },
        { role = "input", category = "Electrical", recipe = "Craft Makeshift HAM Radio" },
        { role = "input", category = "Electrical", recipe = "Craft Makeshift Radio" },
        { role = "input", category = "Electrical", recipe = "Craft Makeshift Walkie Talkie" },
        { role = "input", category = "Electrical", recipe = "Make Noise Maker" },
        { role = "input", category = "Engineer", recipe = "Make Pipe bomb" },
        { role = "input", category = "Electrical", recipe = "Make Remote Controller V1" },
        { role = "input", category = "Electrical", recipe = "Make Remote Controller V2" },
        { role = "input", category = "Electrical", recipe = "Make Remote Controller V3" },
        { role = "input", category = "Electrical", recipe = "Make Remote Trigger" },
        { role = "input", category = "Electrical", recipe = "Make Timer" },
    },
    ["Base.EmptyJar"] = {
        { role = "input", category = "Cooking", recipe = "Make Jar of Bell Peppers" },
        { role = "input", category = "Cooking", recipe = "Make Jar of Broccoli" },
        { role = "input", category = "Cooking", recipe = "Make Jar of Cabbage" },
        { role = "input", category = "Cooking", recipe = "Make Jar of Carrots" },
        { role = "input", category = "Cooking", recipe = "Make Jar of Eggplants" },
        { role = "input", category = "Cooking", recipe = "Make Jar of Leeks" },
        { role = "input", category = "Cooking", recipe = "Make Jar of Potatoes" },
        { role = "input", category = "Cooking", recipe = "Make Jar of Red Radishes" },
        { role = "input", category = "Cooking", recipe = "Make Jar of Tomatoes" },
    },
    ["Base.FishingLine"] = {
        { role = "input", category = "Fishing", recipe = "Fix Fishing Rod" },
        { role = "input", category = "Fishing", recipe = "Make Fishing Rod" },
    },
    ["Base.FishingRodBreak"] = {
        { role = "input", category = "Fishing", recipe = "Fix Fishing Rod" },
    },
    ["Base.FlameTrap"] = {
        { role = "input", category = "Electrical", recipe = "Add Crafted Trigger" },
        { role = "input", category = "Electrical", recipe = "Add Motion Sensor V1" },
        { role = "input", category = "Electrical", recipe = "Add Motion Sensor V2" },
        { role = "input", category = "Electrical", recipe = "Add Motion Sensor V3" },
        { role = "input", category = "Electrical", recipe = "Add Timer" },
    },
    ["Base.Flour"] = {
        { role = "input", category = "Cooking", recipe = "Make Biscuits" },
        { role = "input", category = "Cooking", recipe = "Make Bread Dough" },
        { role = "input", category = "Cooking", recipe = "Make Chocolate Chip Cookie Dough" },
        { role = "input", category = "Cooking", recipe = "Make Chocolate Cookie Dough" },
        { role = "input", category = "Cooking", recipe = "Make Oatmeal Cookie Dough" },
        { role = "input", category = "Cooking", recipe = "Make Shortbread Cookie Dough" },
        { role = "input", category = "Cooking", recipe = "Make Sugar Cookie Dough" },
    },
    ["Base.Fork"] = {
        { role = "input", category = "Survivalist", recipe = "Attach Fork to Spear" },
    },
    ["Base.Frog"] = {
        { role = "input", category = "Cooking", recipe = "Slice Frog" },
    },
    ["Base.GardenSaw"] = {
        { role = "keep", category = "Carpentry", recipe = "Saw Logs2" },
    },
    ["Base.Glue"] = {
        { role = "input", category = "Electrical", recipe = "Make Remote Controller V1" },
        { role = "input", category = "Electrical", recipe = "Make Remote Controller V2" },
        { role = "input", category = "Electrical", recipe = "Make Remote Controller V3" },
        { role = "input", category = "Electrical", recipe = "Make Remote Trigger" },
        { role = "input", category = "Electrical", recipe = "Make Timer" },
    },
    ["Base.GravyMix"] = {
        { role = "input", category = "Cooking", recipe = "Make Gravy" },
    },
    ["Base.GriddlePanFriedVegetables"] = {
        { role = "input", category = "Cooking", recipe = "Empty Griddle Pan" },
    },
    ["Base.GunPowder"] = {
        { role = "input", category = "Smithing", recipe = "Make 223 Bullets" },
        { role = "input", category = "Smithing", recipe = "Make 308 Bullets" },
        { role = "input", category = "Smithing", recipe = "Make 9mm Bullets" },
        { role = "input", category = "Engineer", recipe = "Make Pipe bomb" },
        { role = "input", category = "Smithing", recipe = "Make Shotgun Shells" },
    },
    ["Base.Hairspray"] = {
        { role = "input", category = "Engineer", recipe = "Make Aerosol bomb" },
    },
    ["Base.Ham"] = {
        { role = "input", category = "Cooking", recipe = "Slice Ham" },
    },
    ["Base.HandAxe"] = {
        { role = "keep", category = "Cooking", recipe = "Slice Watermelon" },
    },
    ["Base.HandFork"] = {
        { role = "input", category = "Survivalist", recipe = "Attach Hand Fork to Spear" },
    },
    ["Base.HandTorch"] = {
        { role = "input", category = "Electrical", recipe = "Dismantle Flashlight" },
        { role = "input", category = "Unknown", recipe = "Insert Battery into Flashlight" },
        { role = "keep", category = "Unknown", recipe = "Remove Battery" },
    },
    ["Base.Handle"] = {
        { role = "input", category = "Smithing", recipe = "Make Axe" },
        { role = "input", category = "Smithing", recipe = "Make Shovel" },
        { role = "input", category = "Smithing", recipe = "Make Sledgehammer" },
    },
    ["Base.Headphones"] = {
        { role = "input", category = "Electrical", recipe = "Dismantle Headphones" },
    },
    ["Base.HomeAlarm"] = {
        { role = "input", category = "Electrical", recipe = "Dismantle Home Alarm" },
    },
    ["Base.HuntingKnife"] = {
        { role = "input", category = "Survivalist", recipe = "Attach Hunting Knife to Spear" },
    },
    ["Base.IcePick"] = {
        { role = "input", category = "Survivalist", recipe = "Attach Ice Pick to Spear" },
    },
    ["Base.Icecream"] = {
        { role = "input", category = "Cooking", recipe = "Scoop Ice Cream" },
    },
    ["Base.IronIngot"] = {
        { role = "input", category = "Smithing", recipe = "Make 223 Bullets" },
        { role = "input", category = "Smithing", recipe = "Make 223 Bullets Mold" },
        { role = "input", category = "Smithing", recipe = "Make 308 Bullets" },
        { role = "input", category = "Smithing", recipe = "Make 308 Bullets Mold" },
        { role = "input", category = "Smithing", recipe = "Make 9mm Bullets" },
        { role = "input", category = "Smithing", recipe = "Make 9mm Bullets Mold" },
        { role = "input", category = "Smithing", recipe = "Make Axe" },
        { role = "input", category = "Smithing", recipe = "Make Baking Pan" },
        { role = "input", category = "Smithing", recipe = "Make Baking Tray" },
        { role = "input", category = "Smithing", recipe = "Make Ball Peen Hammer" },
        { role = "input", category = "Smithing", recipe = "Make Butter Knife" },
        { role = "input", category = "Smithing", recipe = "Make Cooking Pot" },
        { role = "input", category = "Smithing", recipe = "Make Door Knob" },
        { role = "input", category = "Smithing", recipe = "Make Fork" },
        { role = "input", category = "Smithing", recipe = "Make Hammer" },
        { role = "input", category = "Smithing", recipe = "Make Hand Shovel" },
        { role = "input", category = "Smithing", recipe = "Make Hinge" },
        { role = "input", category = "Smithing", recipe = "Make Hunting Knife" },
        { role = "input", category = "Smithing", recipe = "Make Kitchen Knife" },
        { role = "input", category = "Smithing", recipe = "Make Letter Opener" },
        { role = "input", category = "Welding", recipe = "Make Metal Bar" },
        { role = "input", category = "Smithing", recipe = "Make Metal Drum" },
        { role = "input", category = "Welding", recipe = "Make Metal Pipe" },
        { role = "input", category = "Smithing", recipe = "Make Nails" },
        { role = "input", category = "Smithing", recipe = "Make Pan" },
        { role = "input", category = "Smithing", recipe = "Make Paperclips" },
        { role = "input", category = "Smithing", recipe = "Make Roasting Pan" },
        { role = "input", category = "Smithing", recipe = "Make Saucepan" },
        { role = "input", category = "Smithing", recipe = "Make Saw" },
        { role = "input", category = "Smithing", recipe = "Make Scissors" },
        { role = "input", category = "Smithing", recipe = "Make Sheet Metal" },
        { role = "input", category = "Smithing", recipe = "Make Shotgun Shells" },
        { role = "input", category = "Smithing", recipe = "Make Shotgun Shells Mold" },
        { role = "input", category = "Smithing", recipe = "Make Shovel" },
        { role = "input", category = "Smithing", recipe = "Make Sledgehammer" },
        { role = "input", category = "Smithing", recipe = "Make Spoon" },
        { role = "input", category = "Smithing", recipe = "Make Suture Needle" },
        { role = "input", category = "Smithing", recipe = "Make Suture Needle Holder" },
        { role = "input", category = "Smithing", recipe = "Make Tongs" },
        { role = "input", category = "Smithing", recipe = "Make Tweezers" },
    },
    ["Base.JarLid"] = {
        { role = "input", category = "Cooking", recipe = "Make Jar of Bell Peppers" },
        { role = "input", category = "Cooking", recipe = "Make Jar of Broccoli" },
        { role = "input", category = "Cooking", recipe = "Make Jar of Cabbage" },
        { role = "input", category = "Cooking", recipe = "Make Jar of Carrots" },
        { role = "input", category = "Cooking", recipe = "Make Jar of Eggplants" },
        { role = "input", category = "Cooking", recipe = "Make Jar of Leeks" },
        { role = "input", category = "Cooking", recipe = "Make Jar of Potatoes" },
        { role = "input", category = "Cooking", recipe = "Make Jar of Red Radishes" },
        { role = "input", category = "Cooking", recipe = "Make Jar of Tomatoes" },
    },
    ["Base.KitchenKnife"] = {
        { role = "input", category = "Survivalist", recipe = "Attach Kitchen Knife to Spear" },
    },
    ["Base.Lard"] = {
        { role = "input", category = "Cooking", recipe = "Make Pie Dough" },
    },
    ["Base.LeatherStripsDirty"] = {
        { role = "input", category = "Health", recipe = "Clean Leather Strips" },
    },
    ["Base.Leek"] = {
        { role = "input", category = "Cooking", recipe = "Make Jar of Leeks" },
    },
    ["Base.LetterOpener"] = {
        { role = "input", category = "Survivalist", recipe = "Attach Letter Opener to Spear" },
    },
    ["Base.LightBulb"] = {
        { role = "input", category = "Electrical", recipe = "Craft Makeshift HAM Radio" },
        { role = "input", category = "Electrical", recipe = "Craft Makeshift Radio" },
        { role = "input", category = "Electrical", recipe = "Craft Makeshift Walkie Talkie" },
    },
    ["Base.LightBulbGreen"] = {
        { role = "input", category = "Electrical", recipe = "Craft Makeshift HAM Radio" },
        { role = "input", category = "Electrical", recipe = "Craft Makeshift Walkie Talkie" },
    },
    ["Base.Log"] = {
        { role = "input", category = "Unknown", recipe = "Drill Plank" },
        { role = "input", category = "Survivalist", recipe = "Make Campfire Kit" },
        { role = "input", category = "Carpentry", recipe = "Make Four-Log Stack" },
        { role = "input", category = "Carpentry", recipe = "Make Three-Log Stack" },
        { role = "input", category = "Carpentry", recipe = "Make Two-Log Stack" },
        { role = "input", category = "Carpentry", recipe = "Saw Logs" },
        { role = "input", category = "Carpentry", recipe = "Saw Logs2" },
        { role = "keep", category = "Cooking", recipe = "Smash Watermelon" },
    },
    ["Base.LogStacks2"] = {
        { role = "input", category = "Carpentry", recipe = "Unstack Logs" },
    },
    ["Base.LogStacks3"] = {
        { role = "input", category = "Carpentry", recipe = "Unstack Logs" },
    },
    ["Base.LogStacks4"] = {
        { role = "input", category = "Carpentry", recipe = "Unstack Logs" },
    },
    ["Base.Machete"] = {
        { role = "input", category = "Survivalist", recipe = "Attach Machete to Spear" },
    },
    ["Base.Magazine"] = {
        { role = "input", category = "Survivalist", recipe = "Make Campfire Kit" },
    },
    ["Base.Margarine"] = {
        { role = "input", category = "Cooking", recipe = "Make Pie Dough" },
    },
    ["Base.MeatCleaver"] = {
        { role = "keep", category = "Cooking", recipe = "Butcher Bird" },
        { role = "keep", category = "Cooking", recipe = "Butcher Rabbit" },
        { role = "keep", category = "Cooking", recipe = "Butcher Small Animal" },
        { role = "keep", category = "Survivalist", recipe = "Create Spear" },
        { role = "keep", category = "Fishing", recipe = "Make Fishing Rod" },
        { role = "keep", category = "Cooking", recipe = "Make Squid Calamari" },
        { role = "keep", category = "Survivalist", recipe = "Make Stake" },
        { role = "keep", category = "Cooking", recipe = "Slice Baloney" },
        { role = "keep", category = "Cooking", recipe = "Slice Bread" },
        { role = "keep", category = "Cooking", recipe = "Slice Cake" },
        { role = "keep", category = "Cooking", recipe = "Slice Fillet" },
        { role = "keep", category = "Cooking", recipe = "Slice Frog" },
        { role = "keep", category = "Cooking", recipe = "Slice Ham" },
        { role = "keep", category = "Cooking", recipe = "Slice Onion" },
        { role = "keep", category = "Cooking", recipe = "Slice Pie" },
        { role = "keep", category = "Cooking", recipe = "Slice Pizza" },
        { role = "keep", category = "Cooking", recipe = "Slice Salami" },
        { role = "keep", category = "Cooking", recipe = "Slice Watermelon" },
    },
    ["Base.MetalBar"] = {
        { role = "input", category = "Smithing", recipe = "Make Crowbar" },
        { role = "input", category = "Smithing", recipe = "Make Golfclub" },
    },
    ["Base.MetalPipe"] = {
        { role = "input", category = "Welding", recipe = "Make Metal Bar" },
        { role = "input", category = "Engineer", recipe = "Make Pipe bomb" },
    },
    ["Base.MincedMeat"] = {
        { role = "input", category = "Cooking", recipe = "Make Meat Patty" },
    },
    ["Base.MotionSensor"] = {
        { role = "input", category = "Electrical", recipe = "Add Motion Sensor V1" },
        { role = "input", category = "Electrical", recipe = "Add Motion Sensor V2" },
        { role = "input", category = "Electrical", recipe = "Add Motion Sensor V3" },
    },
    ["Base.MuffinTray"] = {
        { role = "input", category = "Cooking", recipe = "Make Biscuits" },
        { role = "input", category = "Cooking", recipe = "Prepare Muffins" },
    },
    ["Base.Muffintray_Biscuit"] = {
        { role = "input", category = "Cooking", recipe = "Clean Tray" },
        { role = "input", category = "Cooking", recipe = "Get 6 Biscuits" },
    },
    ["Base.Nails"] = {
        { role = "input", category = "Carpentry", recipe = "Build Drawer" },
        { role = "input", category = "Carpentry", recipe = "Build Spiked Baseball Bat" },
        { role = "input", category = "Carpentry", recipe = "Build Spiked Plank" },
        { role = "input", category = "Fishing", recipe = "Fix Fishing Rod" },
        { role = "input", category = "Fishing", recipe = "Make Fishing Rod" },
        { role = "input", category = "Trapper", recipe = "Make Trap Box" },
        { role = "input", category = "Trapper", recipe = "Make Wooden Box Trap" },
        { role = "input", category = "Unknown", recipe = "Place Nails in Box" },
    },
    ["Base.NailsBox"] = {
        { role = "input", category = "Unknown", recipe = "Open Box of Nails" },
    },
    ["Base.Newspaper"] = {
        { role = "input", category = "Survivalist", recipe = "Make Campfire Kit" },
        { role = "input", category = "Unknown", recipe = "Make Newspaper Hat" },
        { role = "input", category = "Engineer", recipe = "Make Smoke Bomb" },
    },
    ["Base.NoiseTrap"] = {
        { role = "input", category = "Electrical", recipe = "Add Crafted Trigger" },
        { role = "input", category = "Electrical", recipe = "Add Motion Sensor V1" },
        { role = "input", category = "Electrical", recipe = "Add Motion Sensor V2" },
        { role = "input", category = "Electrical", recipe = "Add Motion Sensor V3" },
        { role = "input", category = "Electrical", recipe = "Add Timer" },
    },
    ["Base.OatsRaw"] = {
        { role = "input", category = "Cooking", recipe = "Make Bowl of Oatmeal" },
        { role = "input", category = "Cooking", recipe = "Make Oatmeal Cookie Dough" },
    },
    ["Base.OmeletteRecipe"] = {
        { role = "input", category = "Cooking", recipe = "Empty Frying Pan" },
    },
    ["Base.Onion"] = {
        { role = "input", category = "Cooking", recipe = "Slice Onion" },
    },
    ["Base.OnionRings"] = {
        { role = "input", category = "Cooking", recipe = "Make Fried Onion Rings" },
    },
    ["Base.OpenBeans"] = {
        { role = "input", category = "Cooking", recipe = "Make Bowl of Beans" },
    },
    ["Base.Pan"] = {
        { role = "input", category = "Cooking", recipe = "Prepare Omelette" },
    },
    ["Base.PanFriedVegetables"] = {
        { role = "input", category = "Cooking", recipe = "Empty Frying Pan" },
    },
    ["Base.PanFriedVegetables2"] = {
        { role = "input", category = "Cooking", recipe = "Empty Roasting Pan" },
    },
    ["Base.PancakeMix"] = {
        { role = "input", category = "Cooking", recipe = "Make Pancake" },
    },
    ["Base.Panfish"] = {
        { role = "input", category = "Cooking", recipe = "Slice Fillet" },
    },
    ["Base.Paperclip"] = {
        { role = "input", category = "Fishing", recipe = "Fix Fishing Rod" },
        { role = "input", category = "Fishing", recipe = "Make Fishing Rod" },
        { role = "input", category = "Unknown", recipe = "Place Paperclips in Box" },
    },
    ["Base.PaperclipBox"] = {
        { role = "input", category = "Unknown", recipe = "Open Box of Paperclip" },
    },
    ["Base.Pasta"] = {
        { role = "input", category = "Cooking", recipe = "Place Pasta in Cooking Pot" },
        { role = "input", category = "Cooking", recipe = "Place Pasta in Saucepan" },
    },
    ["Base.PastaPan"] = {
        { role = "input", category = "Cooking", recipe = "Make 2 Bowls of Pasta" },
        { role = "input", category = "Cooking", recipe = "Make 4 Bowls of Pasta" },
    },
    ["Base.PastaPot"] = {
        { role = "input", category = "Cooking", recipe = "Make 2 Bowls of Pasta" },
        { role = "input", category = "Cooking", recipe = "Make 4 Bowls of Pasta" },
    },
    ["Base.Perch"] = {
        { role = "input", category = "Cooking", recipe = "Slice Fillet" },
    },
    ["Base.PieDough"] = {
        { role = "input", category = "Cooking", recipe = "Place Pie in Baking Pan" },
    },
    ["Base.PieWholeRaw"] = {
        { role = "input", category = "Cooking", recipe = "Slice Pie" },
    },
    ["Base.PieWholeRawSweet"] = {
        { role = "input", category = "Cooking", recipe = "Slice Pie" },
    },
    ["Base.Pike"] = {
        { role = "input", category = "Cooking", recipe = "Slice Fillet" },
    },
    ["Base.Pillow"] = {
        { role = "input", category = "Carpentry", recipe = "Make Mattress" },
    },
    ["Base.PipeBomb"] = {
        { role = "input", category = "Electrical", recipe = "Add Crafted Trigger" },
        { role = "input", category = "Electrical", recipe = "Add Motion Sensor V1" },
        { role = "input", category = "Electrical", recipe = "Add Motion Sensor V2" },
        { role = "input", category = "Electrical", recipe = "Add Motion Sensor V3" },
        { role = "input", category = "Electrical", recipe = "Add Timer" },
    },
    ["Base.PizzaRecipe"] = {
        { role = "input", category = "Cooking", recipe = "Slice Pizza" },
    },
    ["Base.PizzaWhole"] = {
        { role = "input", category = "Cooking", recipe = "Slice Pizza" },
    },
    ["Base.Plank"] = {
        { role = "input", category = "Carpentry", recipe = "Build Drawer" },
        { role = "input", category = "Carpentry", recipe = "Build Spiked Plank" },
        { role = "input", category = "Survivalist", recipe = "Create Spear" },
        { role = "input", category = "Unknown", recipe = "Drill Plank" },
        { role = "input", category = "Survivalist", recipe = "Make Campfire Kit" },
        { role = "input", category = "Smithing", recipe = "Make Hunting Knife" },
        { role = "input", category = "Smithing", recipe = "Make Kitchen Knife" },
        { role = "input", category = "Carpentry", recipe = "Make Mortar and Pestle" },
        { role = "input", category = "Smithing", recipe = "Make Saw" },
        { role = "input", category = "Trapper", recipe = "Make Snare Trap" },
        { role = "input", category = "Health", recipe = "Make Splint" },
        { role = "input", category = "Unknown", recipe = "Make Sturdy Stick" },
        { role = "input", category = "Trapper", recipe = "Make Trap Box" },
        { role = "input", category = "Trapper", recipe = "Make Wooden Box Trap" },
        { role = "keep", category = "Cooking", recipe = "Smash Watermelon" },
    },
    ["Base.Plantain"] = {
        { role = "input", category = "Health", recipe = "Make Plantain Poultice" },
    },
    ["Base.PlasterPowder"] = {
        { role = "input", category = "Carpentry", recipe = "Make Bucket of Plaster" },
    },
    ["Base.Pot"] = {
        { role = "input", category = "Cooking", recipe = "Make Pot of Soup" },
    },
    ["Base.PotOfSoup"] = {
        { role = "input", category = "Cooking", recipe = "Make 2 Bowls of Soup" },
        { role = "input", category = "Cooking", recipe = "Make 4 Bowls of Soup" },
    },
    ["Base.PotOfSoupRecipe"] = {
        { role = "input", category = "Cooking", recipe = "Make 2 Bowls of Soup" },
        { role = "input", category = "Cooking", recipe = "Make 4 Bowls of Soup" },
    },
    ["Base.PotOfStew"] = {
        { role = "input", category = "Cooking", recipe = "Make 2 Bowls of Stew" },
        { role = "input", category = "Cooking", recipe = "Make 4 Bowls of Stew" },
    },
    ["Base.PropaneTank"] = {
        { role = "input", category = "Welding", recipe = "Refill Blow Torch" },
    },
    ["Base.Pumpkin"] = {
        { role = "input", category = "Cooking", recipe = "Make Halloween Pumpkin" },
    },
    ["Base.Receiver"] = {
        { role = "input", category = "Electrical", recipe = "Make Remote Trigger" },
    },
    ["Base.Remote"] = {
        { role = "input", category = "Electrical", recipe = "Dismantle TV Remote" },
        { role = "input", category = "Electrical", recipe = "Make Remote Controller V1" },
        { role = "input", category = "Electrical", recipe = "Make Remote Controller V2" },
        { role = "input", category = "Electrical", recipe = "Make Remote Controller V3" },
    },
    ["Base.Rice"] = {
        { role = "input", category = "Cooking", recipe = "Place Rice in Cooking Pot" },
        { role = "input", category = "Cooking", recipe = "Place Rice in Saucepan" },
    },
    ["Base.RicePan"] = {
        { role = "input", category = "Cooking", recipe = "Make 2 Bowls of Rice" },
        { role = "input", category = "Cooking", recipe = "Make 4 Bowls of Rice" },
    },
    ["Base.RicePot"] = {
        { role = "input", category = "Cooking", recipe = "Make 2 Bowls of Rice" },
        { role = "input", category = "Cooking", recipe = "Make 4 Bowls of Rice" },
    },
    ["Base.RippedSheets"] = {
        { role = "input", category = "Health", recipe = "Disinfect Rag" },
        { role = "input", category = "Survivalist", recipe = "Make Campfire Kit" },
        { role = "input", category = "Engineer", recipe = "Make Flame bomb" },
        { role = "input", category = "Unknown", recipe = "Make Molotov Cocktail" },
        { role = "input", category = "Engineer", recipe = "Make Smoke Bomb" },
        { role = "input", category = "Health", recipe = "Make Splint" },
        { role = "input", category = "Survivalist", recipe = "Make Stone Axe" },
        { role = "input", category = "Survivalist", recipe = "Make Stone Hammer" },
        { role = "input", category = "Survivalist", recipe = "Make Stone Knife" },
    },
    ["Base.RippedSheetsDirty"] = {
        { role = "input", category = "Health", recipe = "Clean Rag" },
        { role = "input", category = "Survivalist", recipe = "Make Campfire Kit" },
        { role = "input", category = "Engineer", recipe = "Make Flame bomb" },
        { role = "input", category = "Unknown", recipe = "Make Molotov Cocktail" },
        { role = "input", category = "Engineer", recipe = "Make Smoke Bomb" },
        { role = "input", category = "Health", recipe = "Make Splint" },
        { role = "input", category = "Survivalist", recipe = "Make Stone Axe" },
        { role = "input", category = "Survivalist", recipe = "Make Stone Hammer" },
        { role = "input", category = "Survivalist", recipe = "Make Stone Knife" },
    },
    ["Base.RollingPin"] = {
        { role = "keep", category = "Cooking", recipe = "Make Bread Dough" },
        { role = "keep", category = "Cooking", recipe = "Make Chocolate Chip Cookie Dough" },
        { role = "keep", category = "Cooking", recipe = "Make Chocolate Cookie Dough" },
        { role = "keep", category = "Cooking", recipe = "Make Oatmeal Cookie Dough" },
        { role = "keep", category = "Cooking", recipe = "Make Pizza" },
        { role = "keep", category = "Cooking", recipe = "Make Shortbread Cookie Dough" },
        { role = "keep", category = "Cooking", recipe = "Make Sugar Cookie Dough" },
        { role = "keep", category = "Cooking", recipe = "Place Pie in Baking Pan" },
    },
    ["Base.Rubberducky2"] = {
        { role = "input", category = "Unknown", recipe = "Insert Battery into Duck" },
        { role = "keep", category = "Unknown", recipe = "Remove Battery" },
    },
    ["Base.SackProduce_Apple"] = {
        { role = "input", category = "Unknown", recipe = "Open Sack of Apples" },
    },
    ["Base.SackProduce_BellPepper"] = {
        { role = "input", category = "Unknown", recipe = "Open Sack of Bell Peppers" },
    },
    ["Base.SackProduce_Broccoli"] = {
        { role = "input", category = "Unknown", recipe = "Open Sack of Broccoli" },
    },
    ["Base.SackProduce_Cabbage"] = {
        { role = "input", category = "Unknown", recipe = "Open Sack of Cabbages" },
    },
    ["Base.SackProduce_Carrot"] = {
        { role = "input", category = "Unknown", recipe = "Open Sack of Carrots" },
    },
    ["Base.SackProduce_Cherry"] = {
        { role = "input", category = "Unknown", recipe = "Open Sack of Cherries" },
    },
    ["Base.SackProduce_Corn"] = {
        { role = "input", category = "Unknown", recipe = "Open Sack of Corn" },
    },
    ["Base.SackProduce_Eggplant"] = {
        { role = "input", category = "Unknown", recipe = "Open Sack of Eggplants" },
    },
    ["Base.SackProduce_Grapes"] = {
        { role = "input", category = "Unknown", recipe = "Open Sack of Grapes" },
    },
    ["Base.SackProduce_Leek"] = {
        { role = "input", category = "Unknown", recipe = "Open Sack of Leeks" },
    },
    ["Base.SackProduce_Lettuce"] = {
        { role = "input", category = "Unknown", recipe = "Open Sack of Lettuce" },
    },
    ["Base.SackProduce_Onion"] = {
        { role = "input", category = "Unknown", recipe = "Open Sack of Onions" },
    },
    ["Base.SackProduce_Peach"] = {
        { role = "input", category = "Unknown", recipe = "Open Sack of Peaches" },
    },
    ["Base.SackProduce_Pear"] = {
        { role = "input", category = "Unknown", recipe = "Open Sack of Pears" },
    },
    ["Base.SackProduce_Potato"] = {
        { role = "input", category = "Unknown", recipe = "Open Sack of Potatoes" },
    },
    ["Base.SackProduce_RedRadish"] = {
        { role = "input", category = "Unknown", recipe = "Open Sack of Radishes" },
    },
    ["Base.SackProduce_Strawberry"] = {
        { role = "input", category = "Unknown", recipe = "Open Sack of Strawberries" },
    },
    ["Base.SackProduce_Tomato"] = {
        { role = "input", category = "Unknown", recipe = "Open Sack of Tomatoes" },
    },
    ["Base.Salami"] = {
        { role = "input", category = "Cooking", recipe = "Slice Salami" },
    },
    ["Base.Salt"] = {
        { role = "input", category = "Cooking", recipe = "Make Biscuits" },
        { role = "input", category = "Cooking", recipe = "Make Bread Dough" },
        { role = "input", category = "Cooking", recipe = "Make Pie Dough" },
        { role = "input", category = "Cooking", recipe = "Make Pizza" },
    },
    ["Base.Saw"] = {
        { role = "keep", category = "Unknown", recipe = "Saw Off Double Barrel Shotgun" },
        { role = "keep", category = "Unknown", recipe = "Saw Off Shotgun" },
    },
    ["Base.Scalpel"] = {
        { role = "input", category = "Survivalist", recipe = "Attach Scalpel to Spear" },
    },
    ["Base.Scissors"] = {
        { role = "input", category = "Survivalist", recipe = "Attach Scissors to Spear" },
    },
    ["Base.Screwdriver"] = {
        { role = "input", category = "Survivalist", recipe = "Attach Screwdriver to Spear" },
    },
    ["Base.Screws"] = {
        { role = "input", category = "Unknown", recipe = "Place Screws in Box" },
    },
    ["Base.ScrewsBox"] = {
        { role = "input", category = "Unknown", recipe = "Open Box of Screws" },
    },
    ["Base.Seaweed"] = {
        { role = "input", category = "Cooking", recipe = "Make Maki" },
        { role = "input", category = "Cooking", recipe = "Make Onigiri" },
    },
    ["Base.SharpedStone"] = {
        { role = "keep", category = "Survivalist", recipe = "Create Spear" },
        { role = "keep", category = "Unknown", recipe = "Drill Plank" },
        { role = "input", category = "Survivalist", recipe = "Make Stone Axe" },
        { role = "input", category = "Survivalist", recipe = "Make Stone Knife" },
    },
    ["Base.Sheet"] = {
        { role = "input", category = "Survivalist", recipe = "Make Campfire Kit" },
        { role = "input", category = "Carpentry", recipe = "Make Mattress" },
    },
    ["Base.SheetMetal"] = {
        { role = "input", category = "Welding", recipe = "Make Small Metal Sheet" },
    },
    ["Base.Shotgun"] = {
        { role = "input", category = "Unknown", recipe = "Saw Off Shotgun" },
    },
    ["Base.ShotgunShells"] = {
        { role = "input", category = "Unknown", recipe = "Gather Gunpowder" },
        { role = "input", category = "Unknown", recipe = "Place Shotgun Shells in Box" },
    },
    ["Base.ShotgunShellsBox"] = {
        { role = "input", category = "Unknown", recipe = "Open Box of Shotgun Shells" },
    },
    ["Base.ShotgunShellsMold"] = {
        { role = "keep", category = "Smithing", recipe = "Make Shotgun Shells" },
    },
    ["Base.Shrimp"] = {
        { role = "input", category = "Cooking", recipe = "Make Fried Shrimp" },
    },
    ["Base.SmallSheetMetal"] = {
        { role = "input", category = "Welding", recipe = "Make Metal Sheet" },
    },
    ["Base.SmokeBomb"] = {
        { role = "input", category = "Electrical", recipe = "Add Crafted Trigger" },
        { role = "input", category = "Electrical", recipe = "Add Motion Sensor V1" },
        { role = "input", category = "Electrical", recipe = "Add Motion Sensor V2" },
        { role = "input", category = "Electrical", recipe = "Add Motion Sensor V3" },
        { role = "input", category = "Electrical", recipe = "Add Timer" },
    },
    ["Base.Sparklers"] = {
        { role = "input", category = "Engineer", recipe = "Make Aerosol bomb" },
    },
    ["Base.Spatula"] = {
        { role = "keep", category = "Cooking", recipe = "Make Biscuits" },
        { role = "keep", category = "Cooking", recipe = "Make Bread Dough" },
        { role = "keep", category = "Cooking", recipe = "Make Cake Batter" },
        { role = "keep", category = "Cooking", recipe = "Make Chocolate Chip Cookie Dough" },
        { role = "keep", category = "Cooking", recipe = "Make Chocolate Cookie Dough" },
        { role = "keep", category = "Cooking", recipe = "Make Gravy" },
        { role = "keep", category = "Cooking", recipe = "Make Oatmeal Cookie Dough" },
        { role = "keep", category = "Cooking", recipe = "Make Pancake" },
        { role = "keep", category = "Cooking", recipe = "Make Pie Dough" },
        { role = "keep", category = "Cooking", recipe = "Make Pizza" },
        { role = "keep", category = "Cooking", recipe = "Make Shortbread Cookie Dough" },
        { role = "keep", category = "Cooking", recipe = "Make Sugar Cookie Dough" },
        { role = "keep", category = "Cooking", recipe = "Prepare Muffins" },
        { role = "keep", category = "Cooking", recipe = "Prepare Omelette" },
    },
    ["Base.Speaker"] = {
        { role = "input", category = "Electrical", recipe = "Dismantle Speaker" },
    },
    ["Base.SpearBreadKnife"] = {
        { role = "input", category = "Survivalist", recipe = "Reclaim Bread Knife from Spear" },
    },
    ["Base.SpearButterKnife"] = {
        { role = "input", category = "Survivalist", recipe = "Reclaim Butter Knife from Spear" },
    },
    ["Base.SpearCrafted"] = {
        { role = "input", category = "Survivalist", recipe = "Attach Bread Knife to Spear" },
        { role = "input", category = "Survivalist", recipe = "Attach Butter Knife to Spear" },
        { role = "input", category = "Survivalist", recipe = "Attach Fork to Spear" },
        { role = "input", category = "Survivalist", recipe = "Attach Hand Fork to Spear" },
        { role = "input", category = "Survivalist", recipe = "Attach Hunting Knife to Spear" },
        { role = "input", category = "Survivalist", recipe = "Attach Ice Pick to Spear" },
        { role = "input", category = "Survivalist", recipe = "Attach Kitchen Knife to Spear" },
        { role = "input", category = "Survivalist", recipe = "Attach Letter Opener to Spear" },
        { role = "input", category = "Survivalist", recipe = "Attach Machete to Spear" },
        { role = "input", category = "Survivalist", recipe = "Attach Scalpel to Spear" },
        { role = "input", category = "Survivalist", recipe = "Attach Scissors to Spear" },
        { role = "input", category = "Survivalist", recipe = "Attach Screwdriver to Spear" },
        { role = "input", category = "Survivalist", recipe = "Attach Spoon to Spear" },
    },
    ["Base.SpearFork"] = {
        { role = "input", category = "Survivalist", recipe = "Reclaim Fork from Spear" },
    },
    ["Base.SpearHandFork"] = {
        { role = "input", category = "Survivalist", recipe = "Reclaim Hand Fork from Spear" },
    },
    ["Base.SpearHuntingKnife"] = {
        { role = "input", category = "Survivalist", recipe = "Reclaim Hunting Knife from Spear" },
    },
    ["Base.SpearIcePick"] = {
        { role = "input", category = "Survivalist", recipe = "Reclaim Ice Pick from Spear" },
    },
    ["Base.SpearKnife"] = {
        { role = "input", category = "Survivalist", recipe = "Reclaim Kitchen Knife from Spear" },
    },
    ["Base.SpearLetterOpener"] = {
        { role = "input", category = "Survivalist", recipe = "Reclaim Letter Opener from Spear" },
    },
    ["Base.SpearMachete"] = {
        { role = "input", category = "Survivalist", recipe = "Reclaim Machete from Spear" },
    },
    ["Base.SpearScalpel"] = {
        { role = "input", category = "Survivalist", recipe = "Reclaim Scalpel from Spear" },
    },
    ["Base.SpearScissors"] = {
        { role = "input", category = "Survivalist", recipe = "Reclaim Scissors from Spear" },
    },
    ["Base.SpearScrewdriver"] = {
        { role = "input", category = "Survivalist", recipe = "Reclaim Screwdriver from Spear" },
    },
    ["Base.SpearSpoon"] = {
        { role = "input", category = "Survivalist", recipe = "Reclaim Spoon from Spear" },
    },
    ["Base.Spoon"] = {
        { role = "input", category = "Survivalist", recipe = "Attach Spoon to Spear" },
    },
    ["Base.Squid"] = {
        { role = "input", category = "Cooking", recipe = "Make Squid Calamari" },
    },
    ["Base.Stake"] = {
        { role = "input", category = "Survivalist", recipe = "Make Tent Kit" },
    },
    ["Base.Stone"] = {
        { role = "input", category = "Survivalist", recipe = "Make Stone Hammer" },
    },
    ["Base.Tarp"] = {
        { role = "input", category = "Survivalist", recipe = "Make Tent Kit" },
    },
    ["Base.Thread"] = {
        { role = "input", category = "Carpentry", recipe = "Make Mattress" },
    },
    ["Base.Timer"] = {
        { role = "input", category = "Electrical", recipe = "Make Timer" },
    },
    ["Base.TimerCrafted"] = {
        { role = "input", category = "Electrical", recipe = "Add Timer" },
    },
    ["Base.TinnedBeans"] = {
        { role = "input", category = "Cooking", recipe = "Make Bowl of Beans" },
        { role = "input", category = "Cooking", recipe = "Open Canned Beans" },
    },
    ["Base.TinnedSoup"] = {
        { role = "input", category = "Cooking", recipe = "Make Pot of Soup" },
        { role = "input", category = "Cooking", recipe = "Open Canned Soup" },
    },
    ["Base.TinnedSoupOpen"] = {
        { role = "input", category = "Cooking", recipe = "Make Pot of Soup" },
    },
    ["Base.Tongs"] = {
        { role = "keep", category = "Smithing", recipe = "Make 223 Bullets" },
        { role = "keep", category = "Smithing", recipe = "Make 223 Bullets Mold" },
        { role = "keep", category = "Smithing", recipe = "Make 308 Bullets" },
        { role = "keep", category = "Smithing", recipe = "Make 308 Bullets Mold" },
        { role = "keep", category = "Smithing", recipe = "Make 9mm Bullets" },
        { role = "keep", category = "Smithing", recipe = "Make 9mm Bullets Mold" },
        { role = "keep", category = "Smithing", recipe = "Make Axe" },
        { role = "keep", category = "Smithing", recipe = "Make Baking Pan" },
        { role = "keep", category = "Smithing", recipe = "Make Baking Tray" },
        { role = "keep", category = "Smithing", recipe = "Make Butter Knife" },
        { role = "keep", category = "Smithing", recipe = "Make Cooking Pot" },
        { role = "keep", category = "Smithing", recipe = "Make Crowbar" },
        { role = "keep", category = "Smithing", recipe = "Make Door Knob" },
        { role = "keep", category = "Smithing", recipe = "Make Golfclub" },
        { role = "keep", category = "Smithing", recipe = "Make Hand Shovel" },
        { role = "keep", category = "Smithing", recipe = "Make Hinge" },
        { role = "keep", category = "Smithing", recipe = "Make Hunting Knife" },
        { role = "keep", category = "Smithing", recipe = "Make Kitchen Knife" },
        { role = "keep", category = "Smithing", recipe = "Make Letter Opener" },
        { role = "keep", category = "Smithing", recipe = "Make Metal Drum" },
        { role = "keep", category = "Smithing", recipe = "Make Pan" },
        { role = "keep", category = "Smithing", recipe = "Make Roasting Pan" },
        { role = "keep", category = "Smithing", recipe = "Make Saucepan" },
        { role = "keep", category = "Smithing", recipe = "Make Saw" },
        { role = "keep", category = "Smithing", recipe = "Make Scissors" },
        { role = "keep", category = "Smithing", recipe = "Make Sheet Metal" },
        { role = "keep", category = "Smithing", recipe = "Make Shotgun Shells" },
        { role = "keep", category = "Smithing", recipe = "Make Shotgun Shells Mold" },
        { role = "keep", category = "Smithing", recipe = "Make Shovel" },
        { role = "keep", category = "Smithing", recipe = "Make Sledgehammer" },
        { role = "keep", category = "Smithing", recipe = "Make Suture Needle" },
        { role = "keep", category = "Smithing", recipe = "Make Suture Needle Holder" },
        { role = "keep", category = "Smithing", recipe = "Make Tweezers" },
    },
    ["Base.Torch"] = {
        { role = "input", category = "Electrical", recipe = "Dismantle Flashlight" },
        { role = "input", category = "Unknown", recipe = "Insert Battery into Flashlight" },
        { role = "keep", category = "Unknown", recipe = "Remove Battery" },
    },
    ["Base.TreeBranch"] = {
        { role = "input", category = "Survivalist", recipe = "Create Spear" },
        { role = "input", category = "Health", recipe = "Make Splint" },
        { role = "input", category = "Survivalist", recipe = "Make Stake" },
        { role = "input", category = "Survivalist", recipe = "Make Stone Axe" },
        { role = "input", category = "Survivalist", recipe = "Make Stone Hammer" },
        { role = "input", category = "Survivalist", recipe = "Make Stone Knife" },
    },
    ["Base.TriggerCrafted"] = {
        { role = "input", category = "Electrical", recipe = "Add Crafted Trigger" },
    },
    ["Base.Trout"] = {
        { role = "input", category = "Cooking", recipe = "Slice Fillet" },
    },
    ["Base.TunaTin"] = {
        { role = "input", category = "Cooking", recipe = "Open Canned Tuna" },
    },
    ["Base.Twigs"] = {
        { role = "input", category = "Survivalist", recipe = "Make Campfire Kit" },
    },
    ["Base.Twine"] = {
        { role = "input", category = "Fishing", recipe = "Fix Fishing Rod" },
        { role = "input", category = "Fishing", recipe = "Make Fishing Net" },
        { role = "input", category = "Fishing", recipe = "Make Fishing Rod" },
        { role = "input", category = "Engineer", recipe = "Make Pipe bomb" },
        { role = "input", category = "Trapper", recipe = "Make Snare Trap" },
        { role = "input", category = "Trapper", recipe = "Make Stick Trap" },
        { role = "input", category = "Survivalist", recipe = "Make Stone Axe" },
        { role = "input", category = "Survivalist", recipe = "Make Stone Hammer" },
        { role = "input", category = "Survivalist", recipe = "Make Stone Knife" },
    },
    ["Base.UmbrellaBlack"] = {
        { role = "input", category = "Unknown", recipe = "Close Umbrella" },
    },
    ["Base.UmbrellaBlue"] = {
        { role = "input", category = "Unknown", recipe = "Close Umbrella" },
    },
    ["Base.UmbrellaRed"] = {
        { role = "input", category = "Unknown", recipe = "Close Umbrella" },
    },
    ["Base.UmbrellaWhite"] = {
        { role = "input", category = "Unknown", recipe = "Close Umbrella" },
    },
    ["Base.VideoGame"] = {
        { role = "input", category = "Electrical", recipe = "Dismantle Video Game" },
    },
    ["Base.Vinegar"] = {
        { role = "input", category = "Cooking", recipe = "Make Jar of Bell Peppers" },
        { role = "input", category = "Cooking", recipe = "Make Jar of Broccoli" },
        { role = "input", category = "Cooking", recipe = "Make Jar of Cabbage" },
        { role = "input", category = "Cooking", recipe = "Make Jar of Carrots" },
        { role = "input", category = "Cooking", recipe = "Make Jar of Eggplants" },
        { role = "input", category = "Cooking", recipe = "Make Jar of Leeks" },
        { role = "input", category = "Cooking", recipe = "Make Jar of Potatoes" },
        { role = "input", category = "Cooking", recipe = "Make Jar of Red Radishes" },
        { role = "input", category = "Cooking", recipe = "Make Jar of Tomatoes" },
    },
    ["Base.WaterBottleEmpty"] = {
        { role = "input", category = "Engineer", recipe = "Make Flame bomb" },
    },
    ["Base.WaterPot"] = {
        { role = "input", category = "Health", recipe = "Disinfect Bandage" },
        { role = "input", category = "Health", recipe = "Disinfect Rag" },
        { role = "input", category = "Cooking", recipe = "Place Pasta in Cooking Pot" },
        { role = "input", category = "Cooking", recipe = "Place Rice in Cooking Pot" },
    },
    ["Base.WaterPotPasta"] = {
        { role = "input", category = "Cooking", recipe = "Make 2 Bowls of Pasta" },
        { role = "input", category = "Cooking", recipe = "Make 4 Bowls of Pasta" },
    },
    ["Base.WaterPotRice"] = {
        { role = "input", category = "Cooking", recipe = "Make 2 Bowls of Rice" },
        { role = "input", category = "Cooking", recipe = "Make 4 Bowls of Rice" },
    },
    ["Base.WaterSaucepan"] = {
        { role = "input", category = "Health", recipe = "Disinfect Bandage" },
        { role = "input", category = "Health", recipe = "Disinfect Rag" },
        { role = "input", category = "Cooking", recipe = "Place Pasta in Saucepan" },
        { role = "input", category = "Cooking", recipe = "Place Rice in Saucepan" },
    },
    ["Base.WaterSaucepanPasta"] = {
        { role = "input", category = "Cooking", recipe = "Make 2 Bowls of Pasta" },
        { role = "input", category = "Cooking", recipe = "Make 4 Bowls of Pasta" },
    },
    ["Base.WaterSaucepanRice"] = {
        { role = "input", category = "Cooking", recipe = "Make 2 Bowls of Rice" },
        { role = "input", category = "Cooking", recipe = "Make 4 Bowls of Rice" },
    },
    ["Base.Watermelon"] = {
        { role = "input", category = "Cooking", recipe = "Slice Watermelon" },
        { role = "input", category = "Cooking", recipe = "Smash Watermelon" },
    },
    ["Base.WhiskeyEmpty"] = {
        { role = "input", category = "Unknown", recipe = "HockeyMaskSmashBottle" },
        { role = "input", category = "Unknown", recipe = "Make Molotov Cocktail" },
        { role = "input", category = "Unknown", recipe = "Smash Bottle" },
    },
    ["Base.WhiskeyPetrol"] = {
        { role = "input", category = "Unknown", recipe = "Make Molotov Cocktail" },
    },
    ["Base.WildGarlic"] = {
        { role = "input", category = "Health", recipe = "Make Wild Garlic Poultice" },
    },
    ["Base.WildGarlic2"] = {
        { role = "input", category = "Health", recipe = "Make Wild Garlic Poultice" },
    },
    ["Base.WineEmpty"] = {
        { role = "input", category = "Unknown", recipe = "HockeyMaskSmashBottle" },
        { role = "input", category = "Unknown", recipe = "Make Molotov Cocktail" },
        { role = "input", category = "Unknown", recipe = "Smash Bottle" },
    },
    ["Base.WineEmpty2"] = {
        { role = "input", category = "Unknown", recipe = "HockeyMaskSmashBottle" },
        { role = "input", category = "Unknown", recipe = "Make Molotov Cocktail" },
        { role = "input", category = "Unknown", recipe = "Smash Bottle" },
    },
    ["Base.WinePetrol"] = {
        { role = "input", category = "Unknown", recipe = "Make Molotov Cocktail" },
    },
    ["Base.Wire"] = {
        { role = "input", category = "Trapper", recipe = "Make Cage Trap" },
        { role = "input", category = "Fishing", recipe = "Make Fishing Net" },
    },
    ["Base.WoodAxe"] = {
        { role = "keep", category = "Cooking", recipe = "Slice Watermelon" },
    },
    ["Base.WoodenStick"] = {
        { role = "input", category = "Fishing", recipe = "Make Fishing Rod" },
        { role = "input", category = "Health", recipe = "Make Splint" },
        { role = "input", category = "Trapper", recipe = "Make Stick Trap" },
        { role = "input", category = "Survivalist", recipe = "Make Tent Kit" },
    },
    ["Base.Yeast"] = {
        { role = "input", category = "Cooking", recipe = "Make Bread Dough" },
        { role = "input", category = "Cooking", recipe = "Make Cake Batter" },
        { role = "input", category = "Cooking", recipe = "Make Pizza" },
    },
    ["Radio.CDplayer"] = {
        { role = "input", category = "Electrical", recipe = "Dismantle CD Player" },
    },
    ["Radio.ElectricWire"] = {
        { role = "input", category = "Electrical", recipe = "Craft Makeshift HAM Radio" },
        { role = "input", category = "Electrical", recipe = "Craft Makeshift Radio" },
        { role = "input", category = "Electrical", recipe = "Craft Makeshift Walkie Talkie" },
    },
    ["Radio.HamRadio1"] = {
        { role = "input", category = "Electrical", recipe = "Dismantle HAM Radio" },
    },
    ["Radio.HamRadio2"] = {
        { role = "input", category = "Electrical", recipe = "Dismantle HAM Radio" },
    },
    ["Radio.RadioBlack"] = {
        { role = "input", category = "Electrical", recipe = "Dismantle Radio" },
    },
    ["Radio.RadioReceiver"] = {
        { role = "input", category = "Electrical", recipe = "Craft Makeshift HAM Radio" },
        { role = "input", category = "Electrical", recipe = "Craft Makeshift Radio" },
        { role = "input", category = "Electrical", recipe = "Craft Makeshift Walkie Talkie" },
        { role = "input", category = "Electrical", recipe = "Make Remote Trigger" },
    },
    ["Radio.RadioRed"] = {
        { role = "input", category = "Electrical", recipe = "Dismantle Radio" },
    },
    ["Radio.RadioTransmitter"] = {
        { role = "input", category = "Electrical", recipe = "Craft Makeshift HAM Radio" },
        { role = "input", category = "Electrical", recipe = "Craft Makeshift Walkie Talkie" },
    },
    ["Radio.TvAntique"] = {
        { role = "input", category = "Electrical", recipe = "Dismantle Television" },
    },
    ["Radio.TvBlack"] = {
        { role = "input", category = "Electrical", recipe = "Dismantle Television" },
    },
    ["Radio.TvWideScreen"] = {
        { role = "input", category = "Electrical", recipe = "Dismantle Television" },
    },
    ["Radio.WalkieTalkie1"] = {
        { role = "input", category = "Electrical", recipe = "Dismantle Two-way Radio" },
    },
    ["Radio.WalkieTalkie2"] = {
        { role = "input", category = "Electrical", recipe = "Dismantle Two-way Radio" },
    },
    ["Radio.WalkieTalkie3"] = {
        { role = "input", category = "Electrical", recipe = "Dismantle Two-way Radio" },
    },
    ["Radio.WalkieTalkie4"] = {
        { role = "input", category = "Electrical", recipe = "Dismantle Two-way Radio" },
    },
    ["Radio.WalkieTalkie5"] = {
        { role = "input", category = "Electrical", recipe = "Dismantle Two-way Radio" },
    },
    ["camping.TentPeg"] = {
        { role = "input", category = "Survivalist", recipe = "Make Tent Kit" },
    },
    ["farming.Bacon"] = {
        { role = "input", category = "Cooking", recipe = "Get Bacon Rashers" },
    },
    ["farming.BaconRashers"] = {
        { role = "input", category = "Cooking", recipe = "Get Bacon Bits" },
    },
    ["farming.BroccoliBagSeed"] = {
        { role = "input", category = "Farming", recipe = "Open Packet of Broccoli Seeds" },
    },
    ["farming.BroccoliSeed"] = {
        { role = "input", category = "Farming", recipe = "Put Broccoli Seeds in Packet" },
    },
    ["farming.Cabbage"] = {
        { role = "input", category = "Cooking", recipe = "Make Jar of Cabbage" },
    },
    ["farming.CabbageBagSeed"] = {
        { role = "input", category = "Farming", recipe = "Open Packet of Cabbage Seeds" },
    },
    ["farming.CabbageSeed"] = {
        { role = "input", category = "Farming", recipe = "Put Cabbage Seeds in Packet" },
    },
    ["farming.CarrotBagSeed"] = {
        { role = "input", category = "Farming", recipe = "Open Packet of Carrot Seeds" },
    },
    ["farming.CarrotSeed"] = {
        { role = "input", category = "Farming", recipe = "Put Carrots Seeds in Packet" },
    },
    ["farming.GardeningSprayEmpty"] = {
        { role = "input", category = "Farming", recipe = "Make Flies Cure" },
        { role = "input", category = "Farming", recipe = "Make Mildew Cure" },
    },
    ["farming.Potato"] = {
        { role = "input", category = "Cooking", recipe = "Make Jar of Potatoes" },
    },
    ["farming.PotatoBagSeed"] = {
        { role = "input", category = "Farming", recipe = "Open Packet of Potato Seeds" },
    },
    ["farming.PotatoSeed"] = {
        { role = "input", category = "Farming", recipe = "Put Potato Seeds in Packet" },
    },
    ["farming.RedRadish"] = {
        { role = "input", category = "Cooking", recipe = "Make Jar of Red Radishes" },
    },
    ["farming.RedRadishBagSeed"] = {
        { role = "input", category = "Farming", recipe = "Open Packet of Radish Seeds" },
    },
    ["farming.RedRadishSeed"] = {
        { role = "input", category = "Farming", recipe = "Put Radish Seeds in Packet" },
    },
    ["farming.StrewberrieBagSeed"] = {
        { role = "input", category = "Farming", recipe = "Open Packet of Strawberries Seeds" },
    },
    ["farming.StrewberrieSeed"] = {
        { role = "input", category = "Farming", recipe = "Put Strawberry Seeds in Packet" },
    },
    ["farming.Tomato"] = {
        { role = "input", category = "Cooking", recipe = "Make Jar of Tomatoes" },
    },
    ["farming.TomatoBagSeed"] = {
        { role = "input", category = "Farming", recipe = "Open Packet of Tomato Seeds" },
    },
    ["farming.TomatoSeed"] = {
        { role = "input", category = "Farming", recipe = "Put Tomato Seeds in Packet" },
    },
}

IrisRecipeIndexData.getItemTypes = {
    ["CanOpener"] = {
        "Base.TinOpener",
    },
}

return IrisRecipeIndexData
