-- Auto-generated by export_dvf_3_3_lua_bridge.py.
-- Do not edit manually. Rebuild from the authoritative Layer 3 runtime source.
-- Total runtime entries: 2105
-- Chunks: 11 x <= 200

local data = {}

local chunkModules = {
    "Iris/Data/IrisLayer3Generations/dvf33-c94fb38a933da21b61dee338183652bf486876da6cd36f228c121bd72e1a5925/Chunks/Chunk001",
    "Iris/Data/IrisLayer3Generations/dvf33-c94fb38a933da21b61dee338183652bf486876da6cd36f228c121bd72e1a5925/Chunks/Chunk002",
    "Iris/Data/IrisLayer3Generations/dvf33-c94fb38a933da21b61dee338183652bf486876da6cd36f228c121bd72e1a5925/Chunks/Chunk003",
    "Iris/Data/IrisLayer3Generations/dvf33-c94fb38a933da21b61dee338183652bf486876da6cd36f228c121bd72e1a5925/Chunks/Chunk004",
    "Iris/Data/IrisLayer3Generations/dvf33-c94fb38a933da21b61dee338183652bf486876da6cd36f228c121bd72e1a5925/Chunks/Chunk005",
    "Iris/Data/IrisLayer3Generations/dvf33-c94fb38a933da21b61dee338183652bf486876da6cd36f228c121bd72e1a5925/Chunks/Chunk006",
    "Iris/Data/IrisLayer3Generations/dvf33-c94fb38a933da21b61dee338183652bf486876da6cd36f228c121bd72e1a5925/Chunks/Chunk007",
    "Iris/Data/IrisLayer3Generations/dvf33-c94fb38a933da21b61dee338183652bf486876da6cd36f228c121bd72e1a5925/Chunks/Chunk008",
    "Iris/Data/IrisLayer3Generations/dvf33-c94fb38a933da21b61dee338183652bf486876da6cd36f228c121bd72e1a5925/Chunks/Chunk009",
    "Iris/Data/IrisLayer3Generations/dvf33-c94fb38a933da21b61dee338183652bf486876da6cd36f228c121bd72e1a5925/Chunks/Chunk010",
    "Iris/Data/IrisLayer3Generations/dvf33-c94fb38a933da21b61dee338183652bf486876da6cd36f228c121bd72e1a5925/Chunks/Chunk011",
}

for _, moduleName in ipairs(chunkModules) do
    local chunk = require(moduleName)
    for fullType, entry in pairs(chunk) do
        data[fullType] = entry
    end
end

IrisLayer3Data = data

return data
