-- Iris UseCase Descriptions Data
-- Auto-generated by convert_descriptions_to_lua.py
-- Source: descriptions_by_fulltype.v2.4.json
-- Total fulltypes: 1631
-- Chunks: 9 x <= 200

local IrisUseCaseDescriptions = {}

local chunkModules = {
    "Iris/Data/UseCaseDescriptions/Chunk001",
    "Iris/Data/UseCaseDescriptions/Chunk002",
    "Iris/Data/UseCaseDescriptions/Chunk003",
    "Iris/Data/UseCaseDescriptions/Chunk004",
    "Iris/Data/UseCaseDescriptions/Chunk005",
    "Iris/Data/UseCaseDescriptions/Chunk006",
    "Iris/Data/UseCaseDescriptions/Chunk007",
    "Iris/Data/UseCaseDescriptions/Chunk008",
    "Iris/Data/UseCaseDescriptions/Chunk009",
}

for _, moduleName in ipairs(chunkModules) do
    local chunk = require(moduleName)
    for fullType, entry in pairs(chunk) do
        IrisUseCaseDescriptions[fullType] = entry
    end
end

-- Recipe Requirements Lookup (for runtime fallback)
IrisUseCaseDescriptions._requirementsLookup = require("Iris/Data/UseCaseDescriptions/RequirementsLookup")

return IrisUseCaseDescriptions
