-- Iris Moveables Index Data
-- Auto-generated by build_iris_moveables_index_data.py
-- DO NOT EDIT MANUALLY

local IrisMoveablesIndexData = {}

IrisMoveablesIndexData.registered = {
    ["Base.BallPeenHammer"] = true,
    ["Base.Crowbar"] = true,
    ["Base.FlintKnife"] = true,
    ["Base.GardenFork"] = true,
    ["Base.GardenHoe"] = true,
    ["Base.GardenSaw"] = true,
    ["Base.Hammer"] = true,
    ["Base.HammerStone"] = true,
    ["Base.HandFork"] = true,
    ["Base.HuntingKnife"] = true,
    ["Base.KitchenKnife"] = true,
    ["Base.Machete"] = true,
    ["Base.PickAxe"] = true,
    ["Base.PipeWrench"] = true,
    ["Base.Saw"] = true,
    ["Base.Scissors"] = true,
    ["Base.Screwdriver"] = true,
    ["Base.SharpedStone"] = true,
    ["Base.Shovel"] = true,
    ["Base.Shovel2"] = true,
    ["Base.SnowShovel"] = true,
    ["Base.Wrench"] = true,
    ["farming.HandShovel"] = true,
}

IrisMoveablesIndexData.tagMapping = {
    ["Base.BallPeenHammer"] = "Hammer",
    ["Base.Crowbar"] = "Crowbar",
    ["Base.FlintKnife"] = "SharpKnife",
    ["Base.GardenSaw"] = "Saw",
    ["Base.Hammer"] = "Hammer",
    ["Base.HammerStone"] = "Hammer",
    ["Base.HuntingKnife"] = "SharpKnife",
    ["Base.KitchenKnife"] = "SharpKnife",
    ["Base.Machete"] = "SharpKnife",
    ["Base.PipeWrench"] = "Wrench",
    ["Base.Saw"] = "Saw",
    ["Base.Screwdriver"] = "Screwdriver",
    ["Base.Wrench"] = "Wrench",
}

return IrisMoveablesIndexData
