-- Auto-generated by export_dvf_3_3_lua_bridge.py.
-- Routing metadata only; IrisLayer3DataChunks remains the public facade.
-- sha256 hashes strict UTF-8 text after CRLF/CR -> LF normalization.
return {
    schema_version = "iris_layer3_chunk_range_index_v1",
    entry_count = 2105,
    chunks = {
        { count = 200, first = "Base.223Box", last = "Base.BookElectrician5", module = "Iris/Data/IrisLayer3Generations/dvf33-dfdef534a15eb3cae6b66ae4e7995ebf96a09b9b745082bab3ac2fcfbdd67486/Chunks/Chunk001", sha256 = "4a6f82aec4e6fec31574cc63c6a65a6434574d70762786f4f2d281b6f8de6827" },
        { count = 200, first = "Base.BookFarming1", last = "Base.ChocoCakes", module = "Iris/Data/IrisLayer3Generations/dvf33-dfdef534a15eb3cae6b66ae4e7995ebf96a09b9b745082bab3ac2fcfbdd67486/Chunks/Chunk002", sha256 = "43026f4b2991885b019855f4e2ab570652400ff30376817c267052fc1c694589" },
        { count = 200, first = "Base.Chocolate", last = "Base.FishingNet", module = "Iris/Data/IrisLayer3Generations/dvf33-dfdef534a15eb3cae6b66ae4e7995ebf96a09b9b745082bab3ac2fcfbdd67486/Chunks/Chunk003", sha256 = "4c4ef642f72a5b5089a7f38e850ef076aeacc849a4a16a74a50a820875bef604" },
        { count = 200, first = "Base.FishingRod", last = "Base.Hat_HockeyHelmet", module = "Iris/Data/IrisLayer3Generations/dvf33-dfdef534a15eb3cae6b66ae4e7995ebf96a09b9b745082bab3ac2fcfbdd67486/Chunks/Chunk004", sha256 = "6e835aa920d4c73d9bff941e039067167a50ad59d4cc9dfbdc72689f9de90cea" },
        { count = 200, first = "Base.Hat_HockeyMask", last = "Base.MakeUp_CamoFullFace1", module = "Iris/Data/IrisLayer3Generations/dvf33-dfdef534a15eb3cae6b66ae4e7995ebf96a09b9b745082bab3ac2fcfbdd67486/Chunks/Chunk005", sha256 = "d380fb7c92d8bb7e54845e5b5f825f915e21e05cd1fa2a9db2eb34190c813716" },
        { count = 200, first = "Base.MakeUp_CamoFullFace2", last = "Base.Mov_SmallTable", module = "Iris/Data/IrisLayer3Generations/dvf33-dfdef534a15eb3cae6b66ae4e7995ebf96a09b9b745082bab3ac2fcfbdd67486/Chunks/Chunk006", sha256 = "f2f5f01b75475904bd46b6bced3ac5aa9ef39d30801948a776bd5f73ade29677" },
        { count = 200, first = "Base.Mov_SodaMachine", last = "Base.PillsVitamins", module = "Iris/Data/IrisLayer3Generations/dvf33-dfdef534a15eb3cae6b66ae4e7995ebf96a09b9b745082bab3ac2fcfbdd67486/Chunks/Chunk007", sha256 = "453be0eaa7ade793c21cb24e477d92d51b3887500458696603c8da08c752c63d" },
        { count = 200, first = "Base.Pineapple", last = "Base.Shirt_Bowling_White", module = "Iris/Data/IrisLayer3Generations/dvf33-dfdef534a15eb3cae6b66ae4e7995ebf96a09b9b745082bab3ac2fcfbdd67486/Chunks/Chunk008", sha256 = "39a9efa7860de47f6c2be6981fab1f2925d45b698f0229d5df2037258d058a26" },
        { count = 200, first = "Base.Shirt_CamoDesert", last = "Base.Tissue", module = "Iris/Data/IrisLayer3Generations/dvf33-dfdef534a15eb3cae6b66ae4e7995ebf96a09b9b745082bab3ac2fcfbdd67486/Chunks/Chunk009", sha256 = "6e6473fc648079cfd0921c75b61755fbffbdd1d016de2892ac64f2fe33addbe2" },
        { count = 200, first = "Base.Toast", last = "Base.WineInGlass", module = "Iris/Data/IrisLayer3Generations/dvf33-dfdef534a15eb3cae6b66ae4e7995ebf96a09b9b745082bab3ac2fcfbdd67486/Chunks/Chunk010", sha256 = "6ef6ead969b1778d413307d9166482d75b4bc4b876427a3df82d5e82005c6af0" },
        { count = 105, first = "Base.WinePetrol", last = "farming.WateredCanFull", module = "Iris/Data/IrisLayer3Generations/dvf33-dfdef534a15eb3cae6b66ae4e7995ebf96a09b9b745082bab3ac2fcfbdd67486/Chunks/Chunk011", sha256 = "eede7fdb2104817217df1dc67938691335d882054fd5cd626904d116e0d9e165" },
    },
}
