-- Auto-generated by export_dvf_3_3_lua_bridge.py.
-- Routing metadata only; IrisLayer3DataChunks remains the public facade.
-- sha256 hashes strict UTF-8 text after CRLF/CR -> LF normalization.
return {
    schema_version = "iris_layer3_chunk_range_index_v1",
    entry_count = 2105,
    chunks = {
        { count = 200, first = "Base.223Box", last = "Base.BookElectrician5", module = "Iris/Data/IrisLayer3Generations/dvf33-c94fb38a933da21b61dee338183652bf486876da6cd36f228c121bd72e1a5925/Chunks/Chunk001", sha256 = "cbb5ae10a11fff52016d6e2988623d2b590ab5baef83e3d98dba9ee77d6e1f7d" },
        { count = 200, first = "Base.BookFarming1", last = "Base.ChocoCakes", module = "Iris/Data/IrisLayer3Generations/dvf33-c94fb38a933da21b61dee338183652bf486876da6cd36f228c121bd72e1a5925/Chunks/Chunk002", sha256 = "8b2c9d8ba788b1bdb8ca8d7b0f567bb242cd8b83baa5ee87e3fec0637c974600" },
        { count = 200, first = "Base.Chocolate", last = "Base.FishingNet", module = "Iris/Data/IrisLayer3Generations/dvf33-c94fb38a933da21b61dee338183652bf486876da6cd36f228c121bd72e1a5925/Chunks/Chunk003", sha256 = "5465b56c4cfeee36c195299f207c725ec62a821df3196832165d6034a879b7aa" },
        { count = 200, first = "Base.FishingRod", last = "Base.Hat_HockeyHelmet", module = "Iris/Data/IrisLayer3Generations/dvf33-c94fb38a933da21b61dee338183652bf486876da6cd36f228c121bd72e1a5925/Chunks/Chunk004", sha256 = "dc4276b5d38717ed1df0e5f68d1866dbf2fc92b195e399a8e142245cb47e1aec" },
        { count = 200, first = "Base.Hat_HockeyMask", last = "Base.MakeUp_CamoFullFace1", module = "Iris/Data/IrisLayer3Generations/dvf33-c94fb38a933da21b61dee338183652bf486876da6cd36f228c121bd72e1a5925/Chunks/Chunk005", sha256 = "cca2a390beb418b06ce7eebc0df940f7b06ab435c6015532454dd089cf92503b" },
        { count = 200, first = "Base.MakeUp_CamoFullFace2", last = "Base.Mov_SmallTable", module = "Iris/Data/IrisLayer3Generations/dvf33-c94fb38a933da21b61dee338183652bf486876da6cd36f228c121bd72e1a5925/Chunks/Chunk006", sha256 = "399ae5cdafb85e68841fed6ba8def805fc98e493b218bdacd7a2c5ee0ed65e18" },
        { count = 200, first = "Base.Mov_SodaMachine", last = "Base.PillsVitamins", module = "Iris/Data/IrisLayer3Generations/dvf33-c94fb38a933da21b61dee338183652bf486876da6cd36f228c121bd72e1a5925/Chunks/Chunk007", sha256 = "14a4d23c61385754bf8a0b3b70a26d6efbd02fee773434dfc303e0562bb0cb29" },
        { count = 200, first = "Base.Pineapple", last = "Base.Shirt_Bowling_White", module = "Iris/Data/IrisLayer3Generations/dvf33-c94fb38a933da21b61dee338183652bf486876da6cd36f228c121bd72e1a5925/Chunks/Chunk008", sha256 = "7878d54cf7f03f91f1e81d1012bb1c11f22899bb6e842efcfdd47d3f584d3713" },
        { count = 200, first = "Base.Shirt_CamoDesert", last = "Base.Tissue", module = "Iris/Data/IrisLayer3Generations/dvf33-c94fb38a933da21b61dee338183652bf486876da6cd36f228c121bd72e1a5925/Chunks/Chunk009", sha256 = "8ea22692624bae8021bea837be35be5a47cea5172fd92cc8c325947e0dad8b28" },
        { count = 200, first = "Base.Toast", last = "Base.WineInGlass", module = "Iris/Data/IrisLayer3Generations/dvf33-c94fb38a933da21b61dee338183652bf486876da6cd36f228c121bd72e1a5925/Chunks/Chunk010", sha256 = "f890180f157a9ccb7ea2129692ce4f2a84c5cb191da9316c39c2a8aa17ede62a" },
        { count = 105, first = "Base.WinePetrol", last = "farming.WateredCanFull", module = "Iris/Data/IrisLayer3Generations/dvf33-c94fb38a933da21b61dee338183652bf486876da6cd36f228c121bd72e1a5925/Chunks/Chunk011", sha256 = "f02244631abd6d31d89e215d62d708bf03e87b7d43bfffebae21e43d2950bbf9" },
    },
}
