-- Auto-generated by export_dvf_3_3_lua_bridge.py.
-- Routing metadata only; IrisLayer3DataChunks remains the public facade.
-- sha256 hashes strict UTF-8 text after CRLF/CR -> LF normalization.
return {
    schema_version = "iris_layer3_chunk_range_index_v1",
    entry_count = 2105,
    chunks = {
        { count = 200, first = "Base.223Box", last = "Base.BookElectrician5", module = "Iris/Data/IrisLayer3Generations/dvf33-2a44a0a8d9a2e7f0d9a533ad002b7f691c1bfccec9577fb3356967ec6fd8a00c/Chunks/Chunk001", sha256 = "d4377a81e9f3a7488935c7d02d39d90a8d6802efb205993ea5d40fe9e8b8e728" },
        { count = 200, first = "Base.BookFarming1", last = "Base.ChocoCakes", module = "Iris/Data/IrisLayer3Generations/dvf33-2a44a0a8d9a2e7f0d9a533ad002b7f691c1bfccec9577fb3356967ec6fd8a00c/Chunks/Chunk002", sha256 = "5764fe0b934acc1685ab4fc9323ef52b04d804c4137d659bfc54f0a6ac99451c" },
        { count = 200, first = "Base.Chocolate", last = "Base.FishingNet", module = "Iris/Data/IrisLayer3Generations/dvf33-2a44a0a8d9a2e7f0d9a533ad002b7f691c1bfccec9577fb3356967ec6fd8a00c/Chunks/Chunk003", sha256 = "3f3e18cf7f215c2c991826e11f68e2ac0996db92b154eb5ed2d849569302c773" },
        { count = 200, first = "Base.FishingRod", last = "Base.Hat_HockeyHelmet", module = "Iris/Data/IrisLayer3Generations/dvf33-2a44a0a8d9a2e7f0d9a533ad002b7f691c1bfccec9577fb3356967ec6fd8a00c/Chunks/Chunk004", sha256 = "6aa3492e4bb8917e06b7cd0ff1983122560e16f3bef6bdf253258e880c0ce881" },
        { count = 200, first = "Base.Hat_HockeyMask", last = "Base.MakeUp_CamoFullFace1", module = "Iris/Data/IrisLayer3Generations/dvf33-2a44a0a8d9a2e7f0d9a533ad002b7f691c1bfccec9577fb3356967ec6fd8a00c/Chunks/Chunk005", sha256 = "d824c492b7546106e886c276cd7f07df510f6648f67edf664e345b5d1c94cc8c" },
        { count = 200, first = "Base.MakeUp_CamoFullFace2", last = "Base.Mov_SmallTable", module = "Iris/Data/IrisLayer3Generations/dvf33-2a44a0a8d9a2e7f0d9a533ad002b7f691c1bfccec9577fb3356967ec6fd8a00c/Chunks/Chunk006", sha256 = "acd1b3ee20a2b040773fedf78519bbfc69a86a032ba5826a3ec9c29fb83c67d2" },
        { count = 200, first = "Base.Mov_SodaMachine", last = "Base.PillsVitamins", module = "Iris/Data/IrisLayer3Generations/dvf33-2a44a0a8d9a2e7f0d9a533ad002b7f691c1bfccec9577fb3356967ec6fd8a00c/Chunks/Chunk007", sha256 = "e048c63462f21f5f0e649c0867d1f037e10966d24b907729e4e97c14151f1e7b" },
        { count = 200, first = "Base.Pineapple", last = "Base.Shirt_Bowling_White", module = "Iris/Data/IrisLayer3Generations/dvf33-2a44a0a8d9a2e7f0d9a533ad002b7f691c1bfccec9577fb3356967ec6fd8a00c/Chunks/Chunk008", sha256 = "cc0f153978e22cd5dfa98793728308b285ebf3f1680a1ef9a9a21ade8bbc014c" },
        { count = 200, first = "Base.Shirt_CamoDesert", last = "Base.Tissue", module = "Iris/Data/IrisLayer3Generations/dvf33-2a44a0a8d9a2e7f0d9a533ad002b7f691c1bfccec9577fb3356967ec6fd8a00c/Chunks/Chunk009", sha256 = "1bb9f94eb9d8df3a08c6f4e91b33ac5b6ded2c851be3ae1701447fa8729c5222" },
        { count = 200, first = "Base.Toast", last = "Base.WineInGlass", module = "Iris/Data/IrisLayer3Generations/dvf33-2a44a0a8d9a2e7f0d9a533ad002b7f691c1bfccec9577fb3356967ec6fd8a00c/Chunks/Chunk010", sha256 = "263b59e357d03a2f6727cf86e7e2dd89b119e3fba4b7bf41f4538d3c5da0c281" },
        { count = 105, first = "Base.WinePetrol", last = "farming.WateredCanFull", module = "Iris/Data/IrisLayer3Generations/dvf33-2a44a0a8d9a2e7f0d9a533ad002b7f691c1bfccec9577fb3356967ec6fd8a00c/Chunks/Chunk011", sha256 = "8e7fc5dde1bd32ca22af6a4f506503d48344f99d5a0815360e849028d2fd4a53" },
    },
}
